'use strict';
// Deutsche Version der Karten-Antworten, gleiche Reihenfolge wie CARDS. Die Fragen sind bereits auf Englisch.
window.CARDS_DE = [
"Wir prognostizieren den FCF für 5-10 Jahre, berechnen den Terminal Value, zinsen alles mit dem WACC ab, summieren zum Enterprise Value und ziehen dann Net Debt ab, um Equity Value und Aktienkurs zu erhalten.",
"Das Net Income aus der GuV fließt in die CFS und in die Retained Earnings der Bilanz. In der CFS addieren wir D&A, korrigieren um NWC, ziehen CapEx ab und berücksichtigen Schulden und Aktien. Die Cash-Veränderung geht in die Bilanz und bringt Aktiva und Passiva ins Gleichgewicht.",
"Cash ist ein nicht operatives Vermögen, das der Käufer mit dem Unternehmen erhält und zur Schuldentilgung nutzen kann. Daher ist der reale Preis des operativen Geschäfts niedriger.",
"Gewichtete durchschnittliche Kapitalkosten: Equity-Anteil × Re + Schuldenanteil × Rd × (1 − t). Das ist der Satz, mit dem der FCF im DCF abgezinst wird.",
"CAPM: Re = risikoloser Zins + β × Marktrisikoprämie.",
"Meist die Cost of Equity: Aktionäre tragen mehr Risiko (sie stehen am Ende der Schlange), und Schulden erhalten zusätzlich einen Steuerschild.",
"GuV: EBIT −10, Net Income −10×(1−t). CFS: Net Income niedriger, aber +10 Add-back, also steigt das Cash um 10×t. Bilanz: PP&E −10, Cash +10t, Retained Earnings −10(1−t).",
"Wenn man ein Unternehmen für einen Verkauf oder den Kauf als Ganzes bewertet: Precedents enthalten eine Kontrollprämie.",
"DCF (innerer Wert), Trading Comps, Precedent Transactions, LBO-Analyse (was ein Sponsor zu zahlen bereit ist) sowie Sum-of-the-Parts.",
"Stabile Cashflows, niedrige CapEx, starkes Management, Möglichkeiten zur Margensteigerung, ein klarer Exit und eine nicht übertriebene Bewertung beim Einstieg.",
"Accretive. Der Käufer gibt „teure“ Aktien aus, um „billigen“ Gewinn zu kaufen.",
"Fremdkapital ist dank des Steuerschilds günstiger und verwässert die Aktionäre nicht. Es erhöht aber das Insolvenzrisiko und bringt Covenants mit sich.",
"Gewinn vor Zinsen, Steuern und Abschreibungen. Zeigt die operative Profitabilität ohne Einfluss von Kapitalstruktur und Bilanzierungspolitik. Entspricht nicht dem Cashflow.",
"Unlevered FCF ist vor dem Schuldendienst und steht allen Investoren zur Verfügung (wird im DCF verwendet). Levered FCF ist nach Zinsen und verpflichtenden Zahlungen und gehört den Aktionären.",
"Net Income ≠ Cash. Wachsende Forderungen und Vorräte, hohe CapEx oder Schuldentilgung können das gesamte Cash aufzehren.",
"Schuldzinsen werden vom steuerpflichtigen Gewinn abgezogen, daher sind die realen Fremdkapitalkosten = Rd × (1 − t).",
"Wir bestimmen den Einstiegspreis (EV = EBITDA × Multiple) und die Struktur: Schulden + Sponsor-Equity. Wir prognostizieren den FCF, der in die Schuldentilgung fließt. Beim Exit (meist Jahr 5) berechnen wir den Exit EV, ziehen Net Debt ab und erhalten das Exit Equity. Rendite: MOIC und IRR.",
"Wir nehmen das NI von Käufer und Ziel, addieren Synergien und Finanzierungskosten nach Steuern, berücksichtigen die neuen Aktien und die Abschreibung der Aufwertung. Wir teilen durch die neue Aktienanzahl und vergleichen das Pro-forma-EPS mit dem alten EPS des Käufers.",
"Branche und Geschäftsmodell, Größe, Wachstumsraten, Marge, Geografie, Risiko. Dann normalisieren wir die Zahlen (LTM/NTM, Adjusted EBITDA) und betrachten Median und Quartile der Multiples.",
"Meist Precedent Transactions wegen der Kontrollprämie und der Synergien. Trading Comps liegen üblicherweise niedriger. Ein DCF hängt von Annahmen ab. Ein LBO liefert eine „Preisobergrenze“, die ein Finanzinvestor zahlen kann.",
"Die Annahme, dass der FCF gleichmäßig über das Jahr und nicht am Ende anfällt. Die Zahlungen werden über n − 0,5 Jahre abgezinst, und die Bewertung fällt etwas höher aus.",
"Gordon Growth stützt sich auf eigene Annahmen und Theorie, das Exit-Multiple auf den Markt. Gute Praxis: beides berechnen und abgleichen. Zur Kontrolle berechnen wir das implizite Multiple aus Gordon und das implizite g aus dem Multiple.",
"Unterschiedliches Wachstum, Risiko, Marge, ROIC, Zyklizität, Qualität der Cashflows, Kapitalstruktur. Der Markt zahlt mehr für Wachstum und Stabilität.",
"Das ist die Differenz zwischen Kaufpreis und beizulegendem Zeitwert der identifizierbaren Nettovermögenswerte des Ziels. Entsteht beim Kauf eines Unternehmens. Wird nicht abgeschrieben, aber auf Wertminderung geprüft.",
"Eine latente Steuerverbindlichkeit: Die Steuer im Abschluss ist höher als die zu zahlende Steuer. Bei M&A steigt bei einer Aufwertung von Vermögenswerten der Buchwert, die steuerliche Basis aber nicht, daher entsteht eine DTL.",
"Das EPS steigt, wenn die Earnings Yield (1 / P/E) höher ist als die Fremdkapitalkosten nach Steuern: Es gibt weniger Aktien, und die Zinsen nach Steuern sind niedriger als der Gewinn, den die zurückgekauften Aktien gebracht hätten. Der WACC sinkt zunächst durch Schulden und Steuerschild, steigt dann wegen des Risikos.",
"GuV: Aufwand 10, Net Income sinkt um 10 × (1 − t). CFS: Net Income niedriger, +10 Add-back als nicht zahlungswirksamer Aufwand. Bilanz: Inventory −10, Retained Earnings −10 × (1 − t), Cash steigt um die Steuerersparnis.",
"Der Umsatz ist bereits in der GuV, das Geld aber nicht eingegangen. CFS: Veränderung des NWC −10, CFO niedriger. Bilanz: AR +10, Cash unverändert. Die Bilanz gleicht sich über das Net Income aus.",
"EV/EBITDA hängt nicht von Kapitalstruktur, Steuern und Abschreibungspolitik ab, vergleicht also das operative Geschäft verschiedener Unternehmen und eignet sich für M&A. P/E hängt von den Schulden ab.",
"EV/Revenue oder andere Wachstumskennzahlen (EV/ARR), ein DCF mit Erreichen einer Zielmarge, Vergleich mit Unternehmen in derselben Phase. P/E und EV/EBITDA funktionieren nicht.",
"P/E, P/B, P/TBV und ROE. EV wird nicht verwendet, weil Schulden und Einlagen der Rohstoff des Geschäfts sind. Für einen DCF nutzt man das Dividend Discount Model oder Residual Income.",
"Ein Diagramm mit horizontalen Balken der Bewertungsspannen verschiedener Methoden: DCF, Trading Comps, Precedents, 52-Wochen-Spanne, LBO. Es hilft, die Gesamtspanne des fairen Werts zu erkennen.",
"Der zusätzliche Wert aus dem Zusammenschluss. Kostensynergien (Kostensenkung) sind verlässlicher. Umsatzsynergien (Cross-Selling) sind schwerer zu erreichen und werden oft abgezinst.",
"Eine Gebühr, die das Ziel dem Käufer zahlt, wenn es ein konkurrierendes Angebot annimmt. Sie deckt die Kosten des ersten Käufers und schützt den Deal vor dem Scheitern.",
"Share Purchase: Der Käufer erhält die Aktien und alle Verbindlichkeiten, kein steuerlicher Step-up. Asset Purchase: Der Käufer wählt Vermögenswerte aus und erhält einen Step-up, der Prozess ist aber rechtlich komplizierter.",
"Sell-side: berät den Verkäufer oder Emittenten (Investmentbanken, Equity Research). Buy-side: investiert Kapital (PE, Hedgefonds, Asset Manager).",
"Auswahl der Banken, Due Diligence, Erstellung des Prospekts, Aufsichtsbehörde, Roadshow, Bookbuilding, Preisfestlegung, Platzierung, Handel. Nach dem IPO gilt ein Lock-up. Die Banken erhalten eine Provision und den Greenshoe.",
"M&A-Banker beraten bei Fusionen, Käufen und Verkäufen. ECM hilft bei der Eigenkapitalbeschaffung (IPO, Follow-on). DCM hilft bei der Fremdkapitalbeschaffung (Anleihen, Kredite).",
"Zum Beispiel prognostiziertes EPS × Ziel-KGV, oder ein DCF je Aktie, oder Ziel-EV/EBITDA × EBITDA − Net Debt, geteilt durch die Aktienanzahl. Upside = Kursziel / aktueller Kurs − 1.",
"Die Struktur: Unternehmen und These in 20 Sekunden, warum der Markt falsch liegt, Bewertung mit Spanne, 2-3 Katalysatoren, die wichtigsten Risiken und was dich umstimmen würde, die Empfehlung.",
"Gib ein vorsichtiges Basisszenario mit Argumenten (Inflation, Arbeitsmarkt, EZB/Fed). Zeige dann die Auswirkungen: Diskontsatz, M&A und LBOs, Sektoren (Banken, Immobilien, Tech). Entscheidend ist die Logik der Kette.",
"Nenne die Parteien, Größe, Multiple, Zahlungsform und die Logik des Deals. Gib deine eigene Meinung: warum der Deal sinnvoll ist, wo die Risiken liegen, was eine Analyse nach der Integration zeigen würde.",
"Drei Säulen: intellektuelle Herausforderung (Bewertung, Strukturierung), steile Lernkurve und früh viel Verantwortung, Arbeit an der Schnittstelle von Märkten und Strategie. Untermauere es mit konkreter Erfahrung aus deinem Lebenslauf.",
"In 2 Minuten: Ausbildung und Finanzen, praktische Erfahrung (ACCA, Bank, Compliance), Fähigkeiten, die im IB nützlich sind, und warum genau diese Rolle der nächste Schritt ist. Chronologie plus eine verbindende Idee.",
"Nenne 2-3 konkrete Gründe: Stärken im Sektor oder in der Region, aktuelle Deals, Kultur und die Menschen, mit denen du gesprochen hast. Das zeigt, dass du deine Hausaufgaben gemacht hast.",
"Eine echte Schwäche, keine verkappte Stärke, und Schritte zu ihrer Behebung mit Ergebnis. Zum Beispiel fehlende Modellierungserfahrung und wie du sie durch Kurse und Praxis schließt.",
"Nutze STAR: Situation, deine Aufgabe, deine Handlungen, das Ergebnis mit Zahl. Betone deinen eigenen Beitrag, nicht „wir haben alles gemacht“.",
"Priorisierung nach Dringlichkeit und Wichtigkeit, Erwartungen klären, frühe Zwischenstände, rechtzeitig um Hilfe bitten. Gib ein Beispiel, in dem du bei hoher Last pünktlich geliefert hast.",
"Betone die Stärken: Englisch C1, internationale Erfahrung, analytische Ausbildung, Motivation und Fortschritt im Deutschen. Sei ehrlich zum Niveau und zum Verbesserungsplan, das kommt besser an, als dem Thema auszuweichen.",
"Debt minus Cash und Äquivalente. Zu Debt zählen Bankkredite, Anleihen, manchmal Leasingverbindlichkeiten, Pensionsverpflichtungen und Preferred. Achte aus Konsistenzgründen darauf, welches EBITDA verwendet wird.",
"Die Cash-Basis erfasst Erträge und Aufwendungen bei Geldbewegung. Accrual erfasst sie, wenn sie entstehen (verdient/ausgegeben). Die Konzernberichterstattung nach IFRS und GAAP nutzt Accrual.",
"NWC = operatives Umlaufvermögen − operative kurzfristige Verbindlichkeiten. Im Deal wird ein NWC-Peg vereinbart: das normale Niveau des NWC. Ein Fehlbetrag senkt den Preis, ein Überschuss erhöht ihn.",
"Ein Teil des Preises, der später gezahlt wird, wenn Ziele erreicht werden (Umsatz, EBITDA). Er senkt das Risiko einer Überzahlung und bringt die Positionen von Käufer und Verkäufer bei unsicherem Wachstum näher zusammen.",
"Bedingungen in Kreditverträgen. Maintenance Covenants werden regelmäßig geprüft (Net Debt/EBITDA nicht höher als 4x). Incurrence Covenants werden bei bestimmten Handlungen geprüft (neue Schulden, Dividenden).",
"Fremdkapital ist günstiger als Eigenkapital und bringt einen Steuerschild. Es senkt die Investition des Sponsors und erhöht den IRR, wenn das Asset wächst. Der Nachteil: Risiko, Covenants, Zinszahlungen.",
"Spin-off: Die Aktien einer Tochter werden an die bestehenden Aktionäre verteilt, und es entsteht ein eigenständiges börsennotiertes Unternehmen. Carve-out: Ein Teil der Aktien der Tochter wird an Investoren verkauft (IPO), die Mutter behält meist die Kontrolle.",
"Der EV ändert sich nicht: Der Equity Value sinkt, die Debt steigt um denselben Betrag. Es ändert sich die Kapitalstruktur, nicht der Wert des operativen Geschäfts.",
"Eine Änderung der Kapitalstruktur: zum Beispiel Ersatz eines Teils des Eigenkapitals durch Schulden (Leveraged Recap), Zahlung einer Dividende, Aktienrückkauf, Refinanzierung von Schulden.",
"Das EPS beeinflusst den Aktienkurs und die Wahrnehmung des Deals am Markt. Accretive Deals lassen sich Aktionären leichter erklären. Accretion ist aber keine Wertschöpfung: ROIC und Preis sind entscheidend.",
"Trading Comps spiegeln die aktuellen Kurse börsennotierter Unternehmen ohne Kontrollprämie wider. Transaction Comps spiegeln die Preise von M&A-Deals mit Prämie und Synergien wider.",
"Man schließt einmalige und nicht wiederkehrende Posten aus: Restrukturierung, Rechtskosten, Wertminderungen, untypische Erträge. Manchmal addiert man die Kosten aktienbasierter Vergütung hinzu. Jede Anpassung muss begründet sein.",
];
