'use strict';
// English version of the built-in interview card answers, same order as CARDS in content*.js. The questions are already in English.
const CARDS_EN = [
"We forecast FCF for 5-10 years, calculate the terminal value, discount everything at WACC, sum it up into Enterprise Value, then subtract net debt to get Equity Value and the share price.",
"Net Income from the IS goes into the CFS and into Retained Earnings on the BS. In the CFS we add back D&A, adjust for NWC, subtract CapEx and account for debt and shares. The final change in cash goes onto the BS and balances assets and liabilities.",
"Cash is a non-operating asset that the buyer gets together with the company and can use to repay debt. So the real price of the operating business is lower.",
"The weighted average cost of capital: share of equity × Re + share of debt × Rd × (1 − t). It is the rate at which FCF is discounted in a DCF.",
"CAPM: Re = risk-free rate + β × market risk premium.",
"Usually the cost of equity: shareholders bear more risk (they are last in line), and debt also gets a tax shield.",
"IS: EBIT −10, Net Income −10×(1−t). CFS: Net Income is lower, but +10 add-back, so cash rises by 10×t. BS: PP&E −10, cash +10t, Retained Earnings −10(1−t).",
"When valuing a company for a sale or a purchase of the whole company: precedents include a control premium.",
"DCF (intrinsic value), Trading Comps, Precedent Transactions, LBO analysis (what a sponsor is willing to pay), as well as Sum-of-the-Parts.",
"Stable cash flows, low CapEx, strong management, opportunities to raise the margin, a clear exit, and a not excessively high valuation at entry.",
"Accretive. The buyer issues “expensive” shares to buy “cheap” earnings.",
"Debt is cheaper thanks to the tax shield and does not dilute shareholders. But it raises the risk of bankruptcy and brings covenants.",
"Earnings before interest, taxes, depreciation and amortisation. It shows operating profitability without the influence of capital structure and accounting policy. It is not equal to cash flow.",
"Unlevered FCF is before debt payments and is available to all investors (used in a DCF). Levered FCF is after interest and mandatory payments and belongs to shareholders.",
"Net Income ≠ cash. Growth in receivables and inventory, high CapEx or debt repayment can eat up all the cash.",
"Interest on debt is deducted from taxable profit, so the real cost of debt = Rd × (1 − t).",
"We determine the entry price (EV = EBITDA × multiple) and the structure: debt + sponsor equity. We forecast FCF, which goes to repaying debt. At exit (usually year 5) we calculate Exit EV, subtract net debt and get Exit Equity. Returns: MOIC and IRR.",
"We take the NI of the buyer and the target, add synergies and after-tax financing costs, account for the new shares and write-up depreciation. We divide by the new number of shares and compare pro forma EPS with the buyer's old EPS.",
"Industry and business model, size, growth rates, margin, geography, risk. Then we normalise the figures (LTM/NTM, adjusted EBITDA) and look at the median and quartiles of the multiples.",
"Most often precedent transactions, because of the control premium and synergies. Trading comps are usually lower. A DCF depends on assumptions. An LBO gives a “price ceiling” that a financial sponsor can pay.",
"The assumption that FCF arrives evenly through the year rather than at the end. The flows are discounted over n − 0.5 years, and the valuation comes out slightly higher.",
"Gordon Growth relies on your own assumptions and theory, the exit multiple on the market. Good practice: calculate both and cross-check. To check, we calculate the implied multiple from Gordon and the implied g from the multiple.",
"Different growth rates, risk, margin, ROIC, cyclicality, quality of cash flows, capital structure. The market pays more for growth and stability.",
"It is the difference between the purchase price and the fair value of the target's net identifiable assets. It arises when a business is bought. It is not amortised, but is tested for impairment.",
"A deferred tax liability: the tax in the accounts is higher than the tax payable. In M&A, when assets are written up, the book value rises but the tax base does not, so a DTL is created.",
"EPS rises if the earnings yield (1 / P/E) is higher than the after-tax cost of debt: there are fewer shares, and the after-tax interest is lower than the profit the bought-back shares would have brought. WACC first falls because of the debt and tax shield, then rises because of risk.",
"IS: expense 10, Net Income falls by 10 × (1 − t). CFS: Net Income is lower, +10 add-back as a non-cash expense. BS: Inventory −10, Retained Earnings −10 × (1 − t), cash rises by the tax saving.",
"Revenue is already in the IS, but the cash has not been received. CFS: change in NWC −10, CFO is lower. BS: AR +10, Cash does not change. The balance sheet balances through Net Income.",
"EV/EBITDA does not depend on capital structure, taxes or depreciation policy, so it compares the operating business of different companies and suits M&A. P/E depends on debt.",
"EV/Revenue or other growth metrics (EV/ARR), a DCF reaching a target margin, comparison with peers at the same stages. P/E and EV/EBITDA do not work.",
"P/E, P/B, P/TBV and ROE. EV is not used, because debt and deposits are the raw material of the business. For a DCF they use the Dividend Discount Model or Residual Income.",
"A chart with horizontal bars of valuation ranges from different methods: DCF, trading comps, precedents, 52-week range, LBO. It helps to see the overall range of fair value.",
"The additional value from combining. Cost synergies (cost reduction) are more reliable. Revenue synergies (cross-selling) are harder to achieve and are often discounted.",
"A fee the target pays the buyer if it accepts a competing offer. It compensates the first buyer's costs and protects the deal from collapsing.",
"Stock purchase: the buyer gets the shares and all liabilities, no tax step-up. Asset purchase: the buyer chooses assets and gets a step-up, but the process is more complicated legally.",
"Sell-side: advises the seller or issuer (investment banks, equity research). Buy-side: invests capital (PE, hedge funds, asset managers).",
"Choosing banks, due diligence, preparing the prospectus, the regulator, roadshow, bookbuilding, pricing, placement, trading. After the IPO a lock-up applies. The banks receive a fee and the greenshoe.",
"M&A bankers advise on mergers, purchases and sales. ECM helps raise equity (IPO, follow-on). DCM helps raise debt (bonds, loans).",
"For example, forecast EPS × target P/E, or a DCF per share, or target EV/EBITDA × EBITDA − net debt, divided by the number of shares. Upside = target price / current price − 1.",
"The structure: the company and thesis in 20 seconds, why the market is wrong, valuation with a range, 2-3 catalysts, the main risks and what would make you change your mind, the recommendation.",
"Give a cautious base case with arguments (inflation, the labour market, the ECB/Fed). Then show the impact: the discount rate, M&A and LBOs, sectors (banks, real estate, tech). The main thing is the logic of the chain.",
"Name the parties, size, multiple, form of payment and the logic of the deal. Give your own opinion: why the deal is sensible, where the risks are, what a post-integration analysis would show.",
"Three pillars: an intellectual challenge (valuation, structuring), a steep learning curve and responsibility at early stages, working at the intersection of markets and strategy. Back it up with specific experience from your CV.",
"In 2 minutes: education and finance, practical experience (ACCA, bank, compliance), skills that will be useful in IB, and why this role is the next one. A chronology plus a linking idea.",
"Name 2-3 specific reasons: strengths in the sector or region, recent deals, the culture and the people you have spoken to. It shows that you have done your homework.",
"A real weakness, not a disguised strength, and steps to fix it with a result. For example, a lack of modelling experience and how you are closing it with courses and practice.",
"Use STAR: the situation, your task, your actions, the result with a number. Emphasise your own contribution, not “we all did it”.",
"Prioritising by urgency and importance, clarifying expectations, early interim versions, asking for help in good time. Give an example where you delivered work on time under a heavy load.",
"Stress your strengths: C1 English, international experience, analytical training, motivation and progress in German. Be honest about the level and the improvement plan, it is received better than avoiding the topic.",
"Debt minus Cash and equivalents. Debt includes bank loans, bonds, sometimes lease liabilities, pension obligations and preferred. For consistency, check which EBITDA is being used.",
"Cash basis recognises income and expenses when cash moves. Accrual recognises them when they arise (earned/spent). Corporate reporting under IFRS and GAAP uses accrual.",
"NWC = operating current assets − operating current liabilities. In a deal an NWC peg is agreed: the normal level of NWC. A shortfall reduces the price, an excess increases it.",
"Part of the price that is paid later if targets are reached (revenue, EBITDA). It lowers the risk of overpaying and brings the buyer's and seller's positions closer when growth is uncertain.",
"Conditions in loan agreements. Maintenance covenants are tested regularly (Net Debt/EBITDA no higher than 4x). Incurrence covenants are tested on certain actions (new debt, dividends).",
"Debt is cheaper than equity and gives a tax shield. It reduces the sponsor's investment and raises IRR if the asset grows. The downside: risk, covenants, interest payments.",
"Spin-off: the shares of a subsidiary are handed out to existing shareholders, and a separate public company is formed. Carve-out: part of the subsidiary's shares is sold to investors (an IPO), and the parent usually keeps control.",
"EV does not change: Equity Value falls, Debt rises by the same amount. The capital structure changes, not the value of the operating business.",
"A change in the capital structure: for example, replacing part of equity with debt (a leveraged recap), paying a dividend, a share buyback, refinancing debt.",
"EPS affects the share price and the market's perception of the deal. Accretive deals are easier to explain to shareholders. But accretion is not value creation: ROIC and price matter.",
"Trading comps reflect the current prices of public companies without a control premium. Transaction comps reflect the prices of M&A deals with a premium and synergies.",
"You exclude one-off and non-recurring items: restructuring, legal, impairment, atypical income. Sometimes you add back the cost of share-based compensation. Every adjustment must be justified.",
];
