'use strict';
// Kartların cavablarının Azərbaycan versiyası, CARDS ilə eyni sıra. Suallar artıq ingilis dilindədir.
window.CARDS_AZ = [
"5-10 il üçün FCF proqnozlaşdırırıq, terminal value hesablayırıq, hər şeyi WACC ilə diskontlaşdırırıq, Enterprise Value-da cəmləyirik, sonra net debt çıxıb Equity Value və səhmin qiymətini alırıq.",
"IS-dən Net Income CFS-ə və BS-də Retained Earnings-ə gedir. CFS-də D&A əlavə edirik, NWC-yə görə düzəliş edirik, CapEx çıxırıq, borc və səhmləri nəzərə alırıq. Cash-ın yekun dəyişikliyi BS-ə düşür və aktivlərlə passivləri tarazlaşdırır.",
"Cash qeyri-əməliyyat aktividir, alıcı onu şirkətlə birlikdə alır və borcu ödəmək üçün istifadə edə bilər. Ona görə əməliyyat biznesinin real qiyməti aşağıdır.",
"Kapitalın orta çəkili dəyəri: equity payı × Re + borc payı × Rd × (1 − t). DCF-də FCF-lərin diskontlaşdırıldığı dərəcə.",
"CAPM: Re = risksiz dərəcə + β × bazar riski premiyası.",
"Adətən cost of equity: səhmdarlar daha çox risk daşıyır (onlar növbənin sonundadır), üstəlik borc vergi qalxanı alır.",
"IS: EBIT −10, Net Income −10×(1−t). CFS: Net Income aşağıdır, lakin +10 add-back, yekunda cash 10×t qədər artır. BS: PP&E −10, cash +10t, Retained Earnings −10(1−t).",
"Şirkəti bütövlükdə satmaq və ya almaq üçün qiymətləndirərkən: precedents nəzarət premiyasını daxil edir.",
"DCF (daxili dəyər), Trading Comps, Precedent Transactions, LBO analizi (sponsorun ödəməyə hazır olduğu məbləğ), həmçinin Sum-of-the-Parts.",
"Sabit pul axınları, aşağı CapEx, güclü menecment, marjanı artırmaq imkanları, aydın exit, girişdə həddən artıq yüksək olmayan qiymətləndirmə.",
"Accretive. Alıcı «ucuz» mənfəəti almaq üçün «bahalı» səhmlər buraxır.",
"Borc vergi qalxanı sayəsində ucuzdur və səhmdarların payını durulaşdırmır. Lakin iflas riskini və kovenantları artırır.",
"Faizlər, vergilər və amortizasiyadan əvvəlki mənfəət. Kapital strukturunun və uçot siyasətinin təsiri olmadan əməliyyat mənfəətliliyini göstərir. Cash flow-a bərabər deyil.",
"Unlevered FCF borc ödənişlərindən əvvəldir, bütün investorlar üçün əlçatandır (DCF-də istifadə olunur). Levered FCF faizlər və məcburi ödənişlərdən sonradır, səhmdarlara məxsusdur.",
"Net Income ≠ cash. Debitor borclarının və ehtiyatların artımı, yüksək CapEx və ya borcun ödənilməsi bütün nağd pulu yeyə bilər.",
"Borc üzrə faizlər vergiyə cəlb olunan mənfəətdən çıxılır, ona görə borcun real dəyəri = Rd × (1 − t).",
"Giriş qiymətini (EV = EBITDA × mültiplikator) və strukturu müəyyən edirik: borc + sponsorun equity-si. FCF-i proqnozlaşdırırıq, o borcun ödənilməsinə gedir. Çıxışda (adətən 5-ci il) Exit EV hesablayırıq, net debt çıxırıq və Exit Equity alırıq. Gəlirlilik: MOIC və IRR.",
"Alıcının və hədəfin NI-sini götürürük, vergidən sonra sinerjiləri və maliyyələşdirmə xərclərini əlavə edirik, yeni səhmləri və write-up-ın amortizasiyasını nəzərə alırıq. Yeni səhmlərin sayına bölürük və pro forma EPS-i alıcının köhnə EPS-i ilə müqayisə edirik.",
"Sahə və biznes modeli, ölçü, artım tempi, marja, coğrafiya, risk. Sonra rəqəmləri normallaşdırırıq (LTM/NTM, adjusted EBITDA) və mültiplikatorların medianına və kvartillərinə baxırıq.",
"Ən çox precedent transactions, nəzarət premiyasına və sinerjilərə görə. Trading comps adətən aşağıdır. DCF fərziyyələrdən asılıdır. LBO maliyyə sponsorunun ödəyə biləcəyi «qiymət tavanı» verir.",
"FCF-in ilin sonunda deyil, il ərzində bərabər daxil olması fərziyyəsi. Axınlar n − 0,5 il üzrə diskontlaşdırılır, qiymətləndirmə bir qədər yüksək çıxır.",
"Gordon Growth öz fərziyyələrinə və nəzəriyyəyə, exit multiple isə bazara əsaslanır. Yaxşı praktika: hər ikisini hesablayıb yoxlamaq. Yoxlama üçün Gordon-dan implied multiple, mültiplikatordan implied g hesablayırıq.",
"Fərqli artım tempi, risk, marja, ROIC, tsiklik, pul axınlarının keyfiyyəti, kapital strukturu. Bazar artıma və dayanıqlığa daha çox ödəyir.",
"Bu, satınalma qiyməti ilə hədəfin müəyyən edilə bilən xalis aktivlərinin ədalətli dəyəri arasındakı fərqdir. Biznes alınanda yaranır. Amortizasiya olunmur, lakin dəyərsizləşmə üçün yoxlanılır.",
"Təxirə salınmış vergi öhdəliyi: hesabatdakı vergi ödənilməli vergidən yüksəkdir. M&A-da aktivlərin write-up-ı zamanı balans dəyəri artır, vergi bazası isə yox, ona görə DTL yaranır.",
"Earnings yield (1 / P/E) borcun after-tax dəyərindən yüksək olduqda EPS artır: səhmlər azalır, vergidən sonra faizlər isə geri alınmış səhmlərin gətirəcəyi mənfəətdən azdır. WACC əvvəlcə borc və vergi qalxanı hesabına düşür, sonra riskə görə artır.",
"IS: xərc 10, Net Income 10 × (1 − t) qədər düşür. CFS: Net Income aşağıdır, pulsuz xərc kimi +10 add-back. BS: Inventory −10, Retained Earnings −10 × (1 − t), cash vergi qənaəti qədər artır.",
"Gəlir artıq IS-dədir, lakin pul alınmayıb. CFS: NWC dəyişikliyi −10, CFO aşağıdır. BS: AR +10, Cash dəyişmir. Balans Net Income vasitəsilə tarazlaşır.",
"EV/EBITDA kapital strukturundan, vergilərdən və amortizasiya siyasətindən asılı deyil, ona görə müxtəlif şirkətlərin əməliyyat biznesini müqayisə edir və M&A üçün uyğundur. P/E borcdan asılıdır.",
"EV/Revenue və ya digər artım göstəriciləri (EV/ARR), hədəf marjaya çıxışla DCF, eyni mərhələdəki analoqlarla müqayisə. P/E və EV/EBITDA işləmir.",
"P/E, P/B, P/TBV və ROE. EV işlədilmir, çünki borc və depozitlər biznesin xammalıdır. DCF üçün Dividend Discount Model və ya Residual Income istifadə olunur.",
"Müxtəlif metodlar üzrə qiymətləndirmə diapazonlarının üfüqi zolaqlarla göstərildiyi qrafik: DCF, trading comps, precedents, 52-həftəlik diapazon, LBO. Ədalətli dəyərin ümumi diapazonunu görməyə kömək edir.",
"Birləşmədən əlavə dəyər. Cost sinerjilər (xərclərin azalması) daha etibarlıdır. Revenue sinerjilərə (çarpaz satış) çatmaq çətindir və onlar tez-tez diskontlaşdırılır.",
"Hədəf rəqib təklifi qəbul etdikdə alıcıya ödədiyi haqq. İlk alıcının xərclərini kompensasiya edir və sövdələşməni pozulmadan qoruyur.",
"Stock purchase: alıcı səhmləri və bütün öhdəlikləri alır, vergi step-up yoxdur. Asset purchase: alıcı aktivləri seçir, step-up alır, lakin proses hüquqi baxımdan daha mürəkkəbdir.",
"Sell-side: satıcıya və ya emitentə məsləhət verir (investisiya bankları, equity research). Buy-side: kapital yatırır (PE, hedge fondları, aktiv menecerləri).",
"Bankların seçilməsi, due diligence, prospektin hazırlanması, tənzimləyici, roadshow, bookbuilding, qiymətin müəyyənləşdirilməsi, yerləşdirmə, ticarət. IPO-dan sonra lock-up qüvvədədir. Banklar komissiya və greenshoe alır.",
"M&A bankirləri birləşmə, alış və satışlar üzrə məsləhət verirlər. ECM səhm kapitalının cəlb edilməsinə (IPO, follow-on) kömək edir. DCM borcun cəlb edilməsinə (istiqrazlar, kreditlər) kömək edir.",
"Məsələn, proqnoz EPS × hədəf P/E, və ya bir səhmə DCF, və ya hədəf EV/EBITDA × EBITDA − net debt, səhmlərin sayına bölünməklə. Upside = target price / cari qiymət − 1.",
"Struktur: şirkət və tezis 20 saniyədə, bazar niyə yanılır, diapazonla qiymətləndirmə, 2-3 katalizator, əsas risklər və fikrinizi nə dəyişdirər, tövsiyə.",
"Arqumentlərlə ehtiyatlı baza ssenarisi verin (inflyasiya, əmək bazarı, ECB/FED). Sonra təsiri göstərin: diskont, M&A və LBO, sektorlar (banklar, daşınmaz əmlak, tech). Əsas məsələ zəncirin məntiqidir.",
"Tərəfləri, ölçünü, mültiplikatoru, ödəniş formasını və sövdələşmənin məntiqini adlandırın. Öz fikrinizi bildirin: sövdələşmə niyə məntiqlidir, risklər haradadır, inteqrasiyadan sonrakı analiz nəyi göstərərdi.",
"Üç dayaq: intellektual çağırış (qiymətləndirmə, strukturlaşdırma), dik öyrənmə əyrisi və erkən mərhələlərdə məsuliyyət, bazarlar və strategiyanın kəsişməsində iş. CV-dən konkret təcrübə ilə möhkəmləndirin.",
"2 dəqiqə ərzində: təhsil və maliyyə, praktik təcrübə (ACCA, bank, compliance), IB-də faydalı olacaq bacarıqlar və niyə məhz bu rolun növbəti addım olduğu. Xronologiya üstəgəl birləşdirici ideya.",
"2-3 konkret səbəb deyin: sektor və ya regiondakı güclü tərəflər, son sövdələşmələr, mədəniyyət və danışdığınız insanlar. Ev tapşırığınızı etdiyinizi göstərir.",
"Real zəiflik, gizlədilmiş üstünlük yox, və onu aradan qaldırmaq addımları nəticə ilə. Məsələn, modelləşdirmədə təcrübə çatışmazlığı və onu kurslar və praktika ilə necə doldurmağınız.",
"STAR istifadə edin: vəziyyət, sizin vəzifəniz, sizin hərəkətləriniz, rəqəmlə nəticə. «Hamımız etdik» yox, öz töhfənizi vurğulayın.",
"Təcililik və vacibliyə görə prioritetləşdirmə, gözləntilərin dəqiqləşdirilməsi, erkən aralıq versiyalar, vaxtında kömək istəmək. Yüksək yük altında işi vaxtında təhvil verdiyiniz bir nümunə gətirin.",
"Güclü tərəfləri vurğulayın: C1 ingilis dili, beynəlxalq təcrübə, analitik hazırlıq, motivasiya və alman dilində irəliləyiş. Səviyyə və yaxşılaşdırma planı barədə dürüst olun, bu mövzudan yayınmaqdan daha yaxşı qəbul olunur.",
"Debt minus Cash və ekvivalentlər. Debt-ə bank kreditləri, istiqrazlar, bəzən lease liabilities, pensiya öhdəlikləri və preferred daxildir. Ardıcıllıq üçün hansı EBITDA-nın istifadə olunduğuna baxın.",
"Cash basis gəlir və xərcləri pul hərəkəti zamanı tanıyır. Accrual onları yarandıqda (qazanılanda/xərclənəndə) tanıyır. IFRS və GAAP üzrə korporativ hesabat accrual-dan istifadə edir.",
"NWC = əməliyyat cari aktivləri − əməliyyat cari öhdəlikləri. Sövdələşmədə NWC peg razılaşdırılır: NWC-nin normal səviyyəsi. Çatışmazlıq qiyməti azaldır, artıqlıq artırır.",
"Hədəflərə çatıldıqda (gəlir, EBITDA) sonradan ödənilən qiymətin bir hissəsi. Artıq ödəmə riskini azaldır və qeyri-müəyyən artım zamanı alıcı və satıcının mövqelərini yaxınlaşdırır.",
"Kredit müqavilələrindəki şərtlər. Maintenance covenants müntəzəm yoxlanılır (Net Debt/EBITDA 4x-dən yüksək olmasın). Incurrence covenants müəyyən addımlarda yoxlanılır (yeni borc, dividendlər).",
"Borc equity-dən ucuzdur və vergi qalxanı verir. Sponsorun qoyuluşunu azaldır və aktiv artdıqda IRR-ı yüksəldir. Mənfi cəhət: risk, kovenantlar, faiz ödənişləri.",
"Spin-off: törəmə şirkətin səhmləri mövcud səhmdarlara paylanır, ayrıca açıq şirkət yaranır. Carve-out: törəmənin səhmlərinin bir hissəsi investorlara satılır (IPO), ana şirkət adətən nəzarəti saxlayır.",
"EV dəyişmir: Equity Value düşür, Debt eyni məbləğdə artır. Kapital strukturu dəyişir, əməliyyat biznesinin dəyəri yox.",
"Kapital strukturunun dəyişdirilməsi: məsələn, equity-nin bir hissəsinin borcla əvəzlənməsi (leveraged recap), dividend ödənişi, səhmlərin geri alınması, borcun refinansı.",
"EPS səhmin qiymətinə və bazarın sövdələşməni qavramasına təsir edir. Accretive sövdələşmələri səhmdarlara izah etmək asandır. Lakin accretion dəyər yaratmaq deyil: ROIC və qiymət vacibdir.",
"Trading comps açıq şirkətlərin nəzarət premiyası olmadan cari qiymətlərini əks etdirir. Transaction comps premiya və sinerjilərlə M&A sövdələşmələrinin qiymətlərini əks etdirir.",
"Birdəfəlik və təkrarlanmayan maddələri çıxırsınız: restrukturizasiya, məhkəmə, dəyərsizləşmə, qeyri-adi gəlirlər. Bəzən səhm əsaslı mükafatın dəyərini əlavə edirsiniz. Hər düzəliş əsaslandırılmalıdır.",
];
