'use strict';
// Дополнительные слова (часть 2): язык вакансий (Stellenanzeigen) и процесс отклика.
window.DEU_MORE = (window.DEU_MORE || []).concat([
  // ---- ad: типичные формулировки в вакансиях ----
  ['die Stellenanzeige', 'job posting', 'объявление о вакансии', 'iş elanı', 'ad', 'In der Stellenanzeige steht, welche Sprachkenntnisse erwartet werden.'],
  ['das Anforderungsprofil', 'requirements profile', 'профиль требований к кандидату', 'namizədə tələblər', 'ad', 'Mein Profil passt gut zum Anforderungsprofil der Stelle.'],
  ['Ihre Aufgaben', 'your responsibilities', 'ваши задачи', 'sizin vəzifələriniz', 'ad', 'Zu Ihren Aufgaben gehört die Erstellung von Finanzmodellen.'],
  ['Ihr Profil', 'your profile', 'ваш профиль (что мы ждём)', 'sizin profiliniz', 'ad', 'Ihr Profil: ein laufendes Studium der Wirtschaftswissenschaften.'],
  ['Wir bieten', 'we offer', 'мы предлагаем', 'biz təklif edirik', 'ad', 'Wir bieten flexible Arbeitszeiten und eine faire Vergütung.'],
  ['Sie verfügen über', 'you have, you possess', 'у вас есть', 'sizdə var', 'ad', 'Sie verfügen über erste Erfahrungen im Controlling.'],
  ['Sie bringen mit', 'you bring', 'вы приносите (у вас есть)', 'siz özünüzlə gətirirsiniz', 'ad', 'Sie bringen Begeisterung für Zahlen mit.'],
  ['wünschenswert', 'desirable', 'желательно', 'arzuolunandır', 'ad', 'Erfahrung mit SAP ist wünschenswert.'],
  ['von Vorteil', 'an advantage', 'будет преимуществом', 'üstünlük sayılır', 'ad', 'Deutschkenntnisse sind von Vorteil.'],
  ['idealerweise', 'ideally', 'в идеале', 'ideal halda', 'ad', 'Sie haben idealerweise bereits ein Praktikum absolviert.'],
  ['Deutschkenntnisse in Wort und Schrift', 'German in speaking and writing', 'немецкий устно и письменно', 'yazılı və şifahi alman dili', 'ad', 'Wir erwarten Deutschkenntnisse in Wort und Schrift.'],
  ['verhandlungssicheres Englisch', 'business-fluent English', 'английский на уровне деловых переговоров', 'danışıqlar səviyyəsində ingilis dili', 'ad', 'Sie sprechen verhandlungssicheres Englisch.'],
  ['fließende Deutschkenntnisse', 'fluent German', 'свободное владение немецким', 'səlis alman dili', 'ad', 'Fließende Deutschkenntnisse sind Voraussetzung (meist ab C1).'],
  ['gute Deutschkenntnisse', 'good German skills', 'хороший немецкий', 'yaxşı alman dili', 'ad', 'Gute Deutschkenntnisse entsprechen in der Regel dem Niveau B2.'],
  ['sehr gute Deutschkenntnisse', 'very good German skills', 'очень хороший немецкий', 'çox yaxşı alman dili', 'ad', 'Sehr gute Deutschkenntnisse bedeuten meist C1.'],
  ['Muttersprachniveau', 'native-level proficiency', 'уровень носителя', 'ana dili səviyyəsi', 'ad', 'Deutsch auf Muttersprachniveau wird vorausgesetzt.'],
  ['erste Berufserfahrung', 'first work experience', 'первый опыт работы', 'ilk iş təcrübəsi', 'ad', 'Erste Berufserfahrung durch Praktika ist erwünscht.'],
  ['ein abgeschlossenes Studium', 'a completed degree', 'оконченное высшее образование', 'bitmiş ali təhsil', 'ad', 'Voraussetzung ist ein abgeschlossenes Studium der Betriebswirtschaft.'],
  ['immatrikuliert', 'enrolled (at a university)', 'зачислен в вуз (студент)', 'universitetdə qeydiyyatdadır', 'ad', 'Sie sind an einer Hochschule immatrikuliert.'],
  ['die Werkstudententätigkeit', 'working student position', 'работа для студентов (Werkstudent)', 'tələbə iş yeri (Werkstudent)', 'ad', 'Die Werkstudententätigkeit umfasst bis zu 20 Wochenstunden.'],
  ['das Praktikum', 'internship', 'стажировка', 'təcrübə (staj)', 'ad', 'Das Praktikum dauert sechs Monate.'],
  ['die Abschlussarbeit', 'thesis', 'выпускная работа', 'buraxılış işi', 'ad', 'Wir betreuen auch Abschlussarbeiten im Bereich Finanzen.'],
  ['die Eigeninitiative', 'initiative', 'инициативность', 'təşəbbüskarlıq', 'ad', 'Eigeninitiative und Zuverlässigkeit zeichnen Sie aus.'],
  ['die Eigenverantwortung', 'personal responsibility', 'самостоятельность и ответственность', 'şəxsi məsuliyyət', 'ad', 'Sie arbeiten selbstständig und mit Eigenverantwortung.'],
  ['die Teamfähigkeit', 'ability to work in a team', 'умение работать в команде', 'komandada işləmək bacarığı', 'ad', 'Teamfähigkeit ist uns sehr wichtig.'],
  ['die Kommunikationsstärke', 'strong communication skills', 'коммуникабельность', 'ünsiyyət bacarığı', 'ad', 'Kommunikationsstärke ist im Kundenkontakt entscheidend.'],
  ['analytisches Denkvermögen', 'analytical thinking', 'аналитическое мышление', 'analitik düşüncə', 'ad', 'Sie haben ein ausgeprägtes analytisches Denkvermögen.'],
  ['die strukturierte Arbeitsweise', 'structured way of working', 'структурный подход к работе', 'strukturlu iş üslubu', 'ad', 'Eine strukturierte Arbeitsweise ist für diese Stelle wichtig.'],
  ['der sichere Umgang mit MS Office', 'confident use of MS Office', 'уверенное владение MS Office', 'MS Office-dən əminliklə istifadə', 'ad', 'Der sichere Umgang mit MS Office, vor allem Excel, wird erwartet.'],
  ['die Einarbeitung', 'onboarding, induction', 'введение в должность', 'işə uyğunlaşdırma', 'ad', 'Wir sorgen für eine gründliche Einarbeitung.'],
  ['flexible Arbeitszeiten', 'flexible working hours', 'гибкий график', 'çevik iş saatları', 'ad', 'Wir bieten flexible Arbeitszeiten neben dem Studium.'],
  ['mobiles Arbeiten', 'remote working', 'удалённая работа', 'distant iş', 'ad', 'Mobiles Arbeiten ist an zwei Tagen pro Woche möglich.'],
  ['die Vergütung', 'pay, remuneration', 'вознаграждение', 'əmək haqqı', 'ad', 'Die Vergütung richtet sich nach dem Tarifvertrag.'],
  ['die Wochenarbeitszeit', 'weekly working hours', 'недельное рабочее время', 'həftəlik iş saatı', 'ad', 'Die Wochenarbeitszeit beträgt 20 Stunden.'],
  ['befristet', 'fixed-term', 'срочный', 'müddətli', 'ad', 'Die Stelle ist auf sechs Monate befristet.'],
  ['unbefristet', 'permanent', 'бессрочный', 'müddətsiz', 'ad', 'Wir bieten einen unbefristeten Arbeitsvertrag.'],
  ['die Bewerbungsunterlagen', 'application documents', 'документы для отклика', 'müraciət sənədləri', 'ad', 'Bitte senden Sie Ihre vollständigen Bewerbungsunterlagen per E-Mail.'],
  ['der Lebenslauf', 'CV, résumé', 'резюме', 'CV (həyat yazısı)', 'ad', 'Der Lebenslauf sollte tabellarisch und auf zwei Seiten begrenzt sein.'],
  ['das Anschreiben', 'cover letter', 'сопроводительное письмо', 'müşayiət məktubu', 'ad', 'Im Anschreiben erkläre ich, warum ich zur Stelle passe.'],
  ['das Zeugnis', 'reference, certificate', 'аттестат, рекомендательное письмо', 'sertifikat, arayış', 'ad', 'Bitte fügen Sie Ihre Zeugnisse bei.'],
  ['der Ansprechpartner', 'contact person', 'контактное лицо', 'əlaqə şəxsi', 'ad', 'Ihre Ansprechpartnerin ist Frau Schneider.'],
  ['das Vorstellungsgespräch', 'job interview', 'собеседование', 'iş müsahibəsi', 'ad', 'Das Vorstellungsgespräch findet per Video statt.'],
  ['das Assessment-Center', 'assessment centre', 'ассессмент-центр', 'qiymətləndirmə mərkəzi', 'ad', 'Im Assessment-Center lösen die Kandidaten Fallstudien.'],
  ['die Zusage', 'acceptance, job offer', 'положительный ответ, оффер', 'müsbət cavab, təklif', 'ad', 'Ich habe heute die Zusage für das Praktikum erhalten.'],
  ['die Absage', 'rejection', 'отказ', 'rədd cavabı', 'ad', 'Leider habe ich eine Absage bekommen.'],
  ['der frühestmögliche Eintrittstermin', 'earliest possible start date', 'ближайшая возможная дата выхода', 'ən tez mümkün başlama tarixi', 'ad', 'Bitte nennen Sie uns Ihren frühestmöglichen Eintrittstermin.'],
  ['die Gehaltsvorstellung', 'salary expectation', 'ожидания по зарплате', 'maaş gözləntisi', 'ad', 'Bitte geben Sie Ihre Gehaltsvorstellung an.'],
  ['die Kündigungsfrist', 'notice period', 'срок предупреждения об увольнении', 'bildiriş müddəti', 'ad', 'Meine Kündigungsfrist beträgt vier Wochen.'],
  ['der Berufseinsteiger', 'career starter, entry-level', 'начинающий специалист', 'karyerasına yeni başlayan', 'ad', 'Die Stelle richtet sich an Berufseinsteiger (m/w/d).'],
  ['Wir freuen uns auf Ihre Bewerbung', 'we look forward to your application', 'мы ждём вашего отклика', 'müraciətinizi gözləyirik', 'ad', 'Wir freuen uns auf Ihre Bewerbung über unser Karriereportal.'],
  ['die Chancengleichheit', 'equal opportunities', 'равные возможности', 'bərabər imkanlar', 'ad', 'Wir fördern Chancengleichheit und Vielfalt.'],
  ['die Weiterbildung', 'further training', 'повышение квалификации', 'peşə təkmilləşdirmə', 'ad', 'Wir unterstützen Ihre Weiterbildung mit einem Budget.'],
  ['die Karrieremöglichkeiten', 'career opportunities', 'карьерные возможности', 'karyera imkanları', 'ad', 'Bei uns gibt es gute Karrieremöglichkeiten im Konzern.'],
  // ---- job: ещё про собеседование и работу ----
  ['die Stärke', 'strength', 'сильная сторона', 'güclü cəhət', 'job', 'Meine größte Stärke ist strukturiertes Arbeiten.'],
  ['die Schwäche', 'weakness', 'слабая сторона', 'zəif cəhət', 'job', 'Eine Schwäche von mir ist, dass ich bei Details sehr gründlich bin.'],
  ['die Motivation', 'motivation', 'мотивация', 'motivasiya', 'job', 'Meine Motivation für diese Stelle ist das Interesse an Unternehmensbewertung.'],
  ['die Erfahrung', 'experience', 'опыт', 'təcrübə', 'job', 'Ich habe Erfahrung in der Finanzbuchhaltung gesammelt.'],
  ['die Verantwortung übernehmen', 'to take responsibility', 'брать на себя ответственность', 'məsuliyyət götürmək', 'job', 'Im Praktikum durfte ich früh Verantwortung übernehmen.'],
  ['sich bewerben um', 'to apply for', 'откликаться на', 'müraciət etmək', 'job', 'Ich bewerbe mich um die Stelle als Werkstudent im Controlling.'],
  ['sich vorstellen', 'to introduce oneself', 'представиться', 'özünü təqdim etmək', 'job', 'Ich möchte mich kurz vorstellen.'],
  ['zur Verfügung stehen', 'to be available', 'быть в распоряжении', 'əlçatan olmaq', 'job', 'Ab dem 1. Februar stehe ich Ihnen zur Verfügung.'],
  ['Ich interessiere mich für', 'I am interested in', 'меня интересует', 'mən maraqlanıram', 'job', 'Ich interessiere mich besonders für Unternehmensfinanzierung.'],
  ['Ich arbeite gern im Team.', 'I like working in a team.', 'Мне нравится работать в команде.', 'Mən komandada işləməyi sevirəm.', 'job', 'Ich arbeite gern im Team und übernehme auch eigenständig Aufgaben.'],
  ['Das ist eine gute Frage.', 'That is a good question.', 'Это хороший вопрос.', 'Bu yaxşı sualdır.', 'job', 'Das ist eine gute Frage. Ich würde zuerst die Zahlen prüfen.'],
  ['Könnten Sie das bitte wiederholen?', 'Could you please repeat that?', 'Не могли бы вы повторить?', 'Zəhmət olmasa təkrar edərdiniz?', 'job', 'Entschuldigung, könnten Sie das bitte wiederholen?'],
  ['Ich würde gern wissen, wie', 'I would like to know how', 'я хотел бы узнать, как', 'bilmək istərdim ki, necə', 'job', 'Ich würde gern wissen, wie das Team aufgebaut ist.'],
]);
