'use strict';
// Дополнительные слова для немецкой ветки (часть 1): контроллинг, казначейство, налоги; право, аудит, регулирование.
// Формат строки как в deutsch.js: [немецкий, English, русский, azərbaycanca, категория, пример].
window.DEU_MORE = (window.DEU_MORE || []).concat([
  // ---- ctl: Controlling, Treasury, Steuern ----
  ['das Controlling', 'controlling (management accounting)', 'контроллинг', 'kontrollinq', 'ctl', 'Das Controlling unterstützt die Geschäftsführung mit Zahlen und Prognosen.'],
  ['die Kostenstelle', 'cost center', 'центр затрат', 'xərc mərkəzi', 'ctl', 'Jede Abteilung hat eine eigene Kostenstelle.'],
  ['die Kostenträgerrechnung', 'product costing', 'калькуляция себестоимости продукции', 'məhsulun maya dəyərinin hesablanması', 'ctl', 'Die Kostenträgerrechnung zeigt, was ein einzelnes Produkt kostet.'],
  ['der Deckungsbeitrag', 'contribution margin', 'маржинальный доход', 'marjinal gəlir', 'ctl', 'Der Deckungsbeitrag zeigt, wie viel ein Produkt zur Deckung der Fixkosten beiträgt.'],
  ['die Plan-Ist-Abweichung', 'variance between plan and actual', 'отклонение факта от плана', 'plan ilə fakt arasındakı fərq', 'ctl', 'Wir analysieren jeden Monat die Plan-Ist-Abweichung.'],
  ['das Budget', 'budget', 'бюджет', 'büdcə', 'ctl', 'Das Budget für das nächste Jahr wird im November verabschiedet.'],
  ['die Budgetplanung', 'budget planning', 'бюджетное планирование', 'büdcə planlaşdırması', 'ctl', 'Die Budgetplanung beginnt im Herbst.'],
  ['die Prognose', 'forecast', 'прогноз', 'proqnoz', 'ctl', 'Die Prognose für das Gesamtjahr wurde nach oben angepasst.'],
  ['die Hochrechnung', 'extrapolation, projection', 'экстраполяция (прогноз на год)', 'ekstrapolyasiya (illik proqnoz)', 'ctl', 'Die Hochrechnung basiert auf den Zahlen der ersten sechs Monate.'],
  ['das Reporting', 'reporting', 'управленческая отчётность', 'idarəetmə hesabatı', 'ctl', 'Das monatliche Reporting geht an die Geschäftsleitung.'],
  ['die Kennzahl', 'key figure, KPI', 'показатель (KPI)', 'göstərici (KPI)', 'ctl', 'Die wichtigste Kennzahl ist die EBIT-Marge.'],
  ['die Liquidität', 'liquidity', 'ликвидность', 'likvidlik', 'ctl', 'Die Liquidität des Unternehmens ist angespannt.'],
  ['die Liquiditätsplanung', 'liquidity planning', 'планирование ликвидности', 'likvidlik planlaşdırması', 'ctl', 'Die Liquiditätsplanung zeigt die Zahlungsein- und -ausgänge der nächsten Wochen.'],
  ['das Cash-Management', 'cash management', 'управление денежными средствами', 'nağd vəsaitlərin idarə edilməsi', 'ctl', 'Im Cash-Management werden die Konten der Gesellschaften gebündelt.'],
  ['das Treasury', 'treasury', 'казначейство', 'xəzinədarlıq', 'ctl', 'Das Treasury steuert Liquidität, Währungen und Zinsrisiken.'],
  ['der Zahlungsverkehr', 'payment transactions', 'платёжные операции', 'ödəniş əməliyyatları', 'ctl', 'Der Zahlungsverkehr wird täglich abgestimmt.'],
  ['das Währungsrisiko', 'currency risk', 'валютный риск', 'valyuta riski', 'ctl', 'Exporteure sichern ihr Währungsrisiko oft mit Termingeschäften ab.'],
  ['das Zinsrisiko', 'interest rate risk', 'процентный риск', 'faiz riski', 'ctl', 'Steigende Zinsen erhöhen das Zinsrisiko variabel verzinster Kredite.'],
  ['die Absicherung', 'hedging', 'хеджирование', 'hedcinq', 'ctl', 'Die Absicherung erfolgt über Zins- und Währungsswaps.'],
  ['das Termingeschäft', 'forward transaction', 'срочная сделка (форвард)', 'forvard əqdi', 'ctl', 'Mit einem Termingeschäft wird der Kurs für ein späteres Datum festgelegt.'],
  ['die Rückstellung', 'provision', 'резерв', 'ehtiyat (provizya)', 'ctl', 'Für den Rechtsstreit wurde eine Rückstellung gebildet.'],
  ['die Investitionsrechnung', 'capital budgeting', 'оценка эффективности инвестиций', 'investisiya hesablaması', 'ctl', 'Die Investitionsrechnung vergleicht Auszahlungen und erwartete Einzahlungen.'],
  ['die Amortisationszeit', 'payback period', 'срок окупаемости', 'ödəmə müddəti', 'ctl', 'Die Amortisationszeit der Anlage beträgt vier Jahre.'],
  ['der Kapitalwert', 'net present value (NPV)', 'чистая приведённая стоимость (NPV)', 'xalis cari dəyər (NPV)', 'ctl', 'Ein positiver Kapitalwert spricht für die Investition.'],
  ['der interne Zinsfuß', 'internal rate of return (IRR)', 'внутренняя норма доходности (IRR)', 'daxili gəlirlilik norması (IRR)', 'ctl', 'Der interne Zinsfuß liegt über den Kapitalkosten.'],
  ['die Forderung', 'receivable', 'дебиторская задолженность', 'debitor borcu', 'ctl', 'Die Forderungen aus Lieferungen und Leistungen sind gestiegen.'],
  ['die Verbindlichkeit', 'liability, payable', 'обязательство, кредиторская задолженность', 'öhdəlik, kreditor borcu', 'ctl', 'Die Verbindlichkeiten gegenüber Lieferanten betragen 20 Millionen Euro.'],
  ['das Mahnwesen', 'dunning, collections', 'работа с просроченными платежами', 'gecikmiş ödənişlərlə iş', 'ctl', 'Das Mahnwesen verschickt Zahlungserinnerungen nach 30 Tagen.'],
  ['die Rechnung', 'invoice', 'счёт', 'hesab-faktura', 'ctl', 'Die Rechnung muss innerhalb von 14 Tagen bezahlt werden.'],
  ['die Buchung', 'booking, posting', 'проводка', 'mühasibat yazılışı', 'ctl', 'Jede Buchung braucht einen Beleg.'],
  ['die Abstimmung', 'reconciliation', 'сверка', 'üzləşmə', 'ctl', 'Die Abstimmung der Konten erfolgt zum Monatsende.'],
  ['der Monatsabschluss', 'month-end close', 'закрытие месяца', 'ay sonu bağlanışı', 'ctl', 'Der Monatsabschluss muss bis zum fünften Arbeitstag fertig sein.'],
  ['der Quartalsabschluss', 'quarter-end close', 'закрытие квартала', 'rüb sonu bağlanışı', 'ctl', 'Beim Quartalsabschluss prüfen wir die Rückstellungen.'],
  ['die Umsatzsteuer', 'value added tax (VAT)', 'НДС', 'ƏDV', 'ctl', 'Die Umsatzsteuer beträgt in Deutschland in der Regel 19 Prozent.'],
  ['die Körperschaftsteuer', 'corporate income tax', 'налог на прибыль организаций', 'korporativ gəlir vergisi', 'ctl', 'Die Körperschaftsteuer wird auf den Gewinn der Kapitalgesellschaft erhoben.'],
  ['die Gewerbesteuer', 'trade tax', 'промысловый налог (Gewerbesteuer)', 'sənaye vergisi (Gewerbesteuer)', 'ctl', 'Die Gewerbesteuer fließt an die Gemeinden.'],
  ['die Steuererklärung', 'tax return', 'налоговая декларация', 'vergi bəyannaməsi', 'ctl', 'Die Steuererklärung ist bis Ende Juli abzugeben.'],
  ['der Steuerberater', 'tax advisor', 'налоговый консультант', 'vergi məsləhətçisi', 'ctl', 'Unser Steuerberater prüft die Erklärung vor der Abgabe.'],
  ['die Betriebsprüfung', 'tax audit', 'налоговая проверка', 'vergi yoxlaması', 'ctl', 'Die Betriebsprüfung umfasst die letzten drei Geschäftsjahre.'],
  ['die Verrechnungspreise', 'transfer pricing', 'трансфертные цены', 'transfer qiymətləri', 'ctl', 'Verrechnungspreise müssen marktüblich sein.'],
  ['der HGB-Abschluss', 'HGB financial statements', 'отчётность по HGB', 'HGB üzrə maliyyə hesabatı', 'ctl', 'Der Einzelabschluss wird nach HGB erstellt.'],
  ['die internationale Rechnungslegung', 'international financial reporting', 'международная отчётность (IFRS)', 'beynəlxalq maliyyə hesabatı (IFRS)', 'ctl', 'Der Konzern erstellt seinen Konzernabschluss nach internationaler Rechnungslegung.'],
  ['der Konzernabschluss', 'consolidated financial statements', 'консолидированная отчётность', 'konsolidasiya olunmuş hesabat', 'ctl', 'Der Konzernabschluss fasst alle Tochtergesellschaften zusammen.'],
  ['die Kostenrechnung', 'cost accounting', 'учёт затрат', 'xərclərin uçotu', 'ctl', 'Die Kostenrechnung ist Teil des internen Rechnungswesens.'],
  ['die Fixkosten', 'fixed costs', 'постоянные затраты', 'sabit xərclər', 'ctl', 'Die Fixkosten bleiben unabhängig von der Produktionsmenge gleich.'],
  ['die variablen Kosten', 'variable costs', 'переменные затраты', 'dəyişən xərclər', 'ctl', 'Die variablen Kosten steigen mit der Absatzmenge.'],
  ['die Gewinnschwelle', 'break-even point', 'точка безубыточности', 'zərərsizlik nöqtəsi', 'ctl', 'Ab einem Umsatz von zehn Millionen Euro ist die Gewinnschwelle erreicht.'],
  ['die Marge', 'margin', 'маржа', 'marja', 'ctl', 'Die Marge hat sich im zweiten Quartal verbessert.'],
  ['die Kostensenkung', 'cost reduction', 'снижение затрат', 'xərclərin azaldılması', 'ctl', 'Das Programm zur Kostensenkung spart jährlich fünf Millionen Euro.'],
  // ---- law: Recht, Prüfung, Regulierung ----
  ['die Wirtschaftsprüfung', 'auditing', 'аудит', 'audit', 'law', 'Die Wirtschaftsprüfung ist ein klassischer Einstieg in die Finanzbranche.'],
  ['der Wirtschaftsprüfer', 'auditor, CPA', 'аудитор (Wirtschaftsprüfer)', 'auditor', 'law', 'Der Wirtschaftsprüfer testiert den Jahresabschluss.'],
  ['der Bestätigungsvermerk', 'audit opinion', 'аудиторское заключение', 'audit rəyi', 'law', 'Der Bestätigungsvermerk ist uneingeschränkt erteilt worden.'],
  ['der Prüfungsbericht', 'audit report', 'отчёт аудитора', 'audit hesabatı', 'law', 'Der Prüfungsbericht geht an den Aufsichtsrat.'],
  ['die Sorgfaltsprüfung', 'due diligence', 'комплексная проверка (due diligence)', 'hərtərəfli yoxlama (due diligence)', 'law', 'Vor der Übernahme findet eine umfassende Sorgfaltsprüfung statt.'],
  ['der Datenraum', 'data room', 'виртуальная комната данных', 'məlumat otağı', 'law', 'Alle Unterlagen liegen im virtuellen Datenraum.'],
  ['der Kaufvertrag', 'purchase agreement', 'договор купли-продажи', 'alqı-satqı müqaviləsi', 'law', 'Der Kaufvertrag wurde am Freitag unterzeichnet.'],
  ['die Absichtserklärung', 'letter of intent', 'письмо о намерениях', 'niyyət məktubu', 'law', 'Die Absichtserklärung ist rechtlich meist nicht bindend.'],
  ['die Verschwiegenheitserklärung', 'non-disclosure agreement (NDA)', 'соглашение о неразглашении (NDA)', 'məxfilik müqaviləsi (NDA)', 'law', 'Vor dem Zugang zum Datenraum unterschreibt jeder Bieter eine Verschwiegenheitserklärung.'],
  ['die Gewährleistung', 'warranty', 'гарантии продавца', 'satıcı zəmanəti', 'law', 'Der Verkäufer übernimmt Gewährleistungen für die Richtigkeit der Zahlen.'],
  ['die Haftung', 'liability', 'ответственность', 'məsuliyyət', 'law', 'Die Haftung ist auf den Kaufpreis begrenzt.'],
  ['der Kaufpreis', 'purchase price', 'цена покупки', 'satınalma qiyməti', 'law', 'Der Kaufpreis wird bei Vollzug gezahlt.'],
  ['die Kaufpreisanpassung', 'purchase price adjustment', 'корректировка цены покупки', 'satınalma qiymətinin tənzimlənməsi', 'law', 'Die Kaufpreisanpassung richtet sich nach der Nettoverschuldung zum Stichtag.'],
  ['die Fusion', 'merger', 'слияние', 'birləşmə', 'law', 'Die Fusion der beiden Banken wurde im Frühjahr angekündigt.'],
  ['das Übernahmeangebot', 'takeover offer', 'предложение о поглощении', 'satın alma təklifi', 'law', 'Das Übernahmeangebot liegt 30 Prozent über dem Börsenkurs.'],
  ['der Aufsichtsrat', 'supervisory board', 'наблюдательный совет', 'müşahidə şurası', 'law', 'Der Aufsichtsrat überwacht den Vorstand.'],
  ['der Vorstand', 'management board', 'правление', 'idarə heyəti', 'law', 'Der Vorstand besteht aus vier Mitgliedern.'],
  ['die Geschäftsführung', 'management, managing directors', 'руководство (директора)', 'rəhbərlik (direktorlar)', 'law', 'Die Geschäftsführung entscheidet über die Investition.'],
  ['die Hauptversammlung', 'general meeting of shareholders', 'общее собрание акционеров', 'səhmdarların ümumi yığıncağı', 'law', 'Die Hauptversammlung findet jedes Jahr im Mai statt.'],
  ['der Gesellschafter', 'shareholder, partner', 'участник (учредитель) общества', 'şirkət iştirakçısı', 'law', 'Alle Gesellschafter müssen dem Verkauf zustimmen.'],
  ['das Handelsregister', 'commercial register', 'торговый реестр', 'ticarət reyestri', 'law', 'Die Firma ist im Handelsregister eingetragen.'],
  ['die Kartellbehörde', 'antitrust authority', 'антимонопольный орган', 'antiinhisar orqanı', 'law', 'Die Kartellbehörde prüft die Übernahme.'],
  ['die Fusionskontrolle', 'merger control', 'контроль слияний', 'birləşmələrə nəzarət', 'law', 'Der Zusammenschluss unterliegt der Fusionskontrolle.'],
  ['die Aufsichtsbehörde', 'supervisory authority', 'надзорный орган', 'nəzarət orqanı', 'law', 'Die Bankenaufsicht ist eine Aufsichtsbehörde.'],
  ['die Geldwäsche', 'money laundering', 'отмывание денег', 'pulun yuyulması', 'law', 'Banken müssen Geldwäsche aktiv verhindern.'],
  ['die Kundenidentifizierung', 'customer identification (KYC)', 'идентификация клиента (KYC)', 'müştərinin identifikasiyası (KYC)', 'law', 'Die Kundenidentifizierung ist vor der Kontoeröffnung Pflicht.'],
  ['die Regulierung', 'regulation', 'регулирование', 'tənzimləmə', 'law', 'Die Regulierung der Banken wurde nach der Finanzkrise verschärft.'],
  ['die Eigenkapitalanforderung', 'capital requirement', 'требование к капиталу', 'kapital tələbi', 'law', 'Die Eigenkapitalanforderungen für Banken sind gestiegen.'],
  ['der Insiderhandel', 'insider trading', 'инсайдерская торговля', 'insayder ticarəti', 'law', 'Insiderhandel ist strafbar.'],
  ['die Offenlegung', 'disclosure', 'раскрытие информации', 'məlumatın açıqlanması', 'law', 'Die Offenlegung der Zahlen erfolgt im Bundesanzeiger.'],
  ['die Insolvenz', 'insolvency', 'несостоятельность (банкротство)', 'müflisləşmə', 'law', 'Das Unternehmen hat Insolvenz angemeldet.'],
  ['die Sanierung', 'restructuring, turnaround', 'санация (финансовое оздоровление)', 'sağlamlaşdırma', 'law', 'Die Sanierung des Unternehmens dauert zwei Jahre.'],
  ['der Gläubiger', 'creditor', 'кредитор', 'kreditor', 'law', 'Die Gläubiger stimmen dem Sanierungsplan zu.'],
  ['der Schuldner', 'debtor', 'должник', 'borclu', 'law', 'Der Schuldner kann die Raten nicht mehr zahlen.'],
  ['die Bürgschaft', 'guarantee, surety', 'поручительство', 'zaminlik', 'law', 'Die Bank verlangt eine Bürgschaft der Gesellschafter.'],
  ['die Sicherheit', 'collateral, security', 'обеспечение', 'təminat', 'law', 'Als Sicherheit dient eine Grundschuld auf das Gebäude.'],
  ['die Vertragsklausel', 'contract clause', 'условие договора', 'müqavilə bəndi', 'law', 'Die Klausel regelt die Kündigung im Detail.'],
  ['die Kündigung', 'termination, notice', 'расторжение, увольнение', 'ləğv etmə, işdən çıxarma', 'law', 'Die Kündigung muss schriftlich erfolgen.'],
  ['die Verjährung', 'statute of limitations', 'срок давности', 'müddət keçməsi', 'law', 'Die Verjährung beträgt in der Regel drei Jahre.'],
  ['die Einhaltung der Vorschriften', 'regulatory compliance', 'соблюдение норм (комплаенс)', 'qaydalara əməl etmə (komplayens)', 'law', 'Die Einhaltung der Vorschriften wird jährlich geprüft.'],
]);
