'use strict';
// Дополнительные слова (часть 3): дополнения к темам бухучёта, оценки, M&A, финансирования и рынков.
window.DEU_MORE = (window.DEU_MORE || []).concat([
  // ---- acc ----
  ['das Anlagevermögen', 'fixed assets', 'внеоборотные активы', 'əsas vəsaitlər', 'acc', 'Maschinen und Gebäude gehören zum Anlagevermögen.'],
  ['das Umlaufvermögen', 'current assets', 'оборотные активы', 'dövriyyə aktivləri', 'acc', 'Vorräte und Forderungen zählen zum Umlaufvermögen.'],
  ['das Eigenkapital', 'equity', 'собственный капитал', 'xüsusi kapital', 'acc', 'Die Eigenkapitalquote liegt bei 35 Prozent.'],
  ['das Fremdkapital', 'debt capital, liabilities', 'заёмный капитал', 'borc kapitalı', 'acc', 'Das Fremdkapital besteht vor allem aus Bankdarlehen.'],
  ['die Vorräte', 'inventories', 'запасы', 'ehtiyatlar (inventar)', 'acc', 'Die Vorräte wurden im Quartal abgebaut.'],
  ['die Rücklagen', 'reserves', 'резервы (капитала)', 'ehtiyatlar (kapital)', 'acc', 'Der Gewinn wurde teilweise in die Rücklagen eingestellt.'],
  ['die Bilanzsumme', 'total assets', 'валюта баланса', 'balans cəmi', 'acc', 'Die Bilanzsumme beträgt 2,4 Milliarden Euro.'],
  ['die Anschaffungskosten', 'acquisition cost', 'первоначальная стоимость', 'əldəetmə dəyəri', 'acc', 'Die Anlage wird zu Anschaffungskosten bilanziert.'],
  ['der Buchwert', 'book value', 'балансовая стоимость', 'balans dəyəri', 'acc', 'Der Buchwert des Eigenkapitals liegt unter dem Marktwert.'],
  ['der beizulegende Zeitwert', 'fair value', 'справедливая стоимость', 'ədalətli dəyər', 'acc', 'Finanzinstrumente werden zum beizulegenden Zeitwert bewertet.'],
  ['die stillen Reserven', 'hidden reserves', 'скрытые резервы', 'gizli ehtiyatlar', 'acc', 'Beim Verkauf werden stille Reserven aufgedeckt.'],
  ['der Firmenwert', 'goodwill', 'гудвилл', 'qudvil (şöhrət dəyəri)', 'acc', 'Der Firmenwert entsteht, wenn der Kaufpreis den Buchwert übersteigt.'],
  ['die Wertminderung', 'impairment', 'обесценение', 'dəyərsizləşmə', 'acc', 'Auf den Firmenwert wurde eine Wertminderung erfasst.'],
  ['das Betriebsergebnis', 'operating result', 'операционный результат', 'əməliyyat nəticəsi', 'acc', 'Das Betriebsergebnis verbesserte sich um zehn Prozent.'],
  ['das Finanzergebnis', 'financial result', 'финансовый результат', 'maliyyə nəticəsi', 'acc', 'Das Finanzergebnis ist durch hohe Zinsen belastet.'],
  ['die Umsatzerlöse', 'revenue (HGB line item)', 'выручка (статья по HGB)', 'satış gəlirləri', 'acc', 'Die Umsatzerlöse stiegen auf 850 Millionen Euro.'],
  ['der Materialaufwand', 'cost of materials', 'материальные затраты', 'material xərcləri', 'acc', 'Der Materialaufwand ist wegen höherer Rohstoffpreise gestiegen.'],
  ['der Personalaufwand', 'personnel expenses', 'расходы на персонал', 'kadr xərcləri', 'acc', 'Der Personalaufwand macht 40 Prozent der Kosten aus.'],
  ['das Working Capital', 'working capital', 'оборотный капитал', 'iş kapitalı', 'acc', 'Wachstum bindet Working Capital.'],
  ['der operative Cashflow', 'operating cash flow', 'операционный денежный поток', 'əməliyyat pul axını', 'acc', 'Der operative Cashflow deckt die Investitionen vollständig.'],
  ['der freie Cashflow', 'free cash flow', 'свободный денежный поток', 'sərbəst pul axını', 'acc', 'Der freie Cashflow wird für Dividenden und Schuldentilgung genutzt.'],
  ['die Rechnungsabgrenzung', 'prepaid and deferred items (accruals)', 'расходы/доходы будущих периодов', 'gələcək dövrlərin xərc və gəlirləri', 'acc', 'Die Miete für das nächste Quartal steht in der Rechnungsabgrenzung.'],
  ['die latenten Steuern', 'deferred taxes', 'отложенные налоги', 'təxirə salınmış vergilər', 'acc', 'Unterschiede zwischen Handels- und Steuerbilanz führen zu latenten Steuern.'],
  ['der Anhang', 'notes to the financial statements', 'приложение к отчётности (примечания)', 'hesabatlara qeydlər', 'acc', 'Der Anhang erläutert die Bilanzierungsmethoden.'],
  ['der Lagebericht', 'management report', 'отчёт руководства', 'rəhbərlik hesabatı', 'acc', 'Der Lagebericht beschreibt Geschäftsverlauf und Risiken.'],
  ['die Segmentberichterstattung', 'segment reporting', 'сегментная отчётность', 'seqment hesabatı', 'acc', 'Die Segmentberichterstattung zeigt die Ergebnisse je Geschäftsbereich.'],
  // ---- val ----
  ['der Unternehmenswert', 'enterprise value', 'стоимость предприятия (EV)', 'müəssisənin dəyəri (EV)', 'val', 'Der Unternehmenswert umfasst Eigenkapital und Nettoverschuldung.'],
  ['der Barwert', 'present value', 'приведённая стоимость', 'cari dəyər', 'val', 'Der Barwert der künftigen Zahlungen beträgt 90 Millionen Euro.'],
  ['der Endwert', 'terminal value', 'терминальная стоимость', 'terminal dəyər', 'val', 'Der Endwert macht etwa 70 Prozent des Unternehmenswerts aus.'],
  ['die Abzinsung', 'discounting', 'дисконтирование', 'diskontlaşdırma', 'val', 'Bei der Abzinsung werden künftige Zahlungen auf heute umgerechnet.'],
  ['der Diskontierungssatz', 'discount rate', 'ставка дисконтирования', 'diskont dərəcəsi', 'val', 'Ein höherer Diskontierungssatz senkt den Barwert.'],
  ['die Kapitalkosten', 'cost of capital', 'стоимость капитала', 'kapital dəyəri', 'val', 'Die Kapitalkosten liegen bei acht Prozent.'],
  ['die Eigenkapitalkosten', 'cost of equity', 'стоимость собственного капитала', 'xüsusi kapitalın dəyəri', 'val', 'Die Eigenkapitalkosten werden mit dem CAPM berechnet.'],
  ['die Fremdkapitalkosten', 'cost of debt', 'стоимость заёмного капитала', 'borc kapitalının dəyəri', 'val', 'Die Fremdkapitalkosten sind wegen der Steuerersparnis niedriger.'],
  ['die Kapitalstruktur', 'capital structure', 'структура капитала', 'kapital strukturu', 'val', 'Die Kapitalstruktur beeinflusst die Kapitalkosten.'],
  ['die Marktkapitalisierung', 'market capitalization', 'рыночная капитализация', 'bazar kapitallaşması', 'val', 'Die Marktkapitalisierung beträgt zwölf Milliarden Euro.'],
  ['die Vergleichsunternehmen', 'peer companies, comparables', 'сопоставимые компании', 'müqayisəli şirkətlər', 'val', 'Wir wählen Vergleichsunternehmen aus derselben Branche.'],
  ['das Kurs-Gewinn-Verhältnis', 'price/earnings ratio (P/E)', 'коэффициент P/E', 'qiymət/qazanc nisbəti (P/E)', 'val', 'Das Kurs-Gewinn-Verhältnis liegt bei 15.'],
  ['die Kontrollprämie', 'control premium', 'премия за контроль', 'nəzarət mükafatı', 'val', 'Bei Übernahmen wird meist eine Kontrollprämie gezahlt.'],
  ['die Sensitivitätsanalyse', 'sensitivity analysis', 'анализ чувствительности', 'həssaslıq təhlili', 'val', 'Die Sensitivitätsanalyse zeigt die Wirkung von Zins und Wachstum.'],
  ['die Annahme', 'assumption', 'допущение', 'fərziyyə', 'val', 'Die Annahmen des Modells sollten transparent sein.'],
  ['der Planungszeitraum', 'forecast period', 'горизонт прогнозирования', 'proqnoz dövrü', 'val', 'Der Planungszeitraum umfasst fünf Jahre.'],
  ['die ewige Rente', 'perpetuity', 'бессрочная рента', 'daimi renta', 'val', 'Der Endwert wird als ewige Rente berechnet.'],
  ['die Wachstumsrate', 'growth rate', 'темп роста', 'artım tempi', 'val', 'Die langfristige Wachstumsrate liegt bei zwei Prozent.'],
  ['der risikolose Zinssatz', 'risk-free rate', 'безрисковая ставка', 'risksiz faiz dərəcəsi', 'val', 'Als risikoloser Zinssatz dient die Rendite zehnjähriger Bundesanleihen.'],
  ['die Marktrisikoprämie', 'market risk premium', 'рыночная премия за риск', 'bazar risk mükafatı', 'val', 'Die Marktrisikoprämie wird oft mit fünf bis sechs Prozent angesetzt.'],
  ['die Nettoverschuldung', 'net debt', 'чистый долг', 'xalis borc', 'val', 'Die Nettoverschuldung ist das Fremdkapital abzüglich liquider Mittel.'],
  ['das Ertragswertverfahren', 'income approach (capitalized earnings method)', 'доходный подход (метод капитализации доходов)', 'gəlir yanaşması', 'val', 'In Deutschland ist das Ertragswertverfahren in Gutachten weit verbreitet.'],
  ['die Multiplikatormethode', 'multiples method', 'метод мультипликаторов', 'multiplikatorlar metodu', 'val', 'Bei der Multiplikatormethode vergleicht man Kennzahlen ähnlicher Firmen.'],
  ['die Bewertungsspanne', 'valuation range', 'диапазон оценки', 'qiymətləndirmə aralığı', 'val', 'Die Bewertungsspanne reicht von 80 bis 100 Millionen Euro.'],
  // ---- ma ----
  ['der Verkäufer', 'seller', 'продавец', 'satıcı', 'ma', 'Der Verkäufer möchte einen möglichst hohen Preis erzielen.'],
  ['der Käufer', 'buyer', 'покупатель', 'alıcı', 'ma', 'Der Käufer prüft das Unternehmen sehr genau.'],
  ['der Bieter', 'bidder', 'участник торгов, претендент', 'iddiaçı (təklif verən)', 'ma', 'Drei Bieter sind in die zweite Runde gekommen.'],
  ['die Zielgesellschaft', 'target company', 'целевая компания', 'hədəf şirkət', 'ma', 'Die Zielgesellschaft ist im Maschinenbau tätig.'],
  ['der Finanzinvestor', 'financial investor', 'финансовый инвестор', 'maliyyə investoru', 'ma', 'Ein Finanzinvestor kauft Unternehmen, um sie später wieder zu verkaufen.'],
  ['der strategische Investor', 'strategic investor', 'стратегический инвестор', 'strateji investor', 'ma', 'Ein strategischer Investor erwartet Synergien.'],
  ['die Synergien', 'synergies', 'синергия', 'sinerjilər', 'ma', 'Die erwarteten Synergien liegen bei 50 Millionen Euro.'],
  ['die Integration', 'integration', 'интеграция', 'inteqrasiya', 'ma', 'Die Integration beider Firmen dauert drei Jahre.'],
  ['die Ausgliederung', 'carve-out, spin-off', 'выделение (carve-out)', 'ayrılma (carve-out)', 'ma', 'Die Ausgliederung des Geschäftsbereichs ist für Herbst geplant.'],
  ['der Börsengang', 'IPO', 'выход на биржу (IPO)', 'birjaya çıxış (IPO)', 'ma', 'Der Börsengang soll im nächsten Jahr stattfinden.'],
  ['die Kapitalerhöhung', 'capital increase', 'увеличение капитала', 'kapitalın artırılması', 'ma', 'Die Kapitalerhöhung stärkt die Eigenkapitalbasis.'],
  ['der Verkaufsprozess', 'sale process', 'процесс продажи', 'satış prosesi', 'ma', 'Der Verkaufsprozess läuft in mehreren Runden.'],
  ['das Informationsmemorandum', 'information memorandum', 'информационный меморандум', 'məlumat memorandumu', 'ma', 'Das Informationsmemorandum beschreibt das Unternehmen im Detail.'],
  ['die Unterzeichnung', 'signing', 'подписание', 'imzalanma', 'ma', 'Zwischen Unterzeichnung und Vollzug vergehen oft einige Monate.'],
  ['der Vollzug', 'closing', 'закрытие сделки', 'əqdin bağlanması (closing)', 'ma', 'Der Vollzug steht unter dem Vorbehalt der Kartellfreigabe.'],
  ['die Kaufpreisallokation', 'purchase price allocation', 'распределение цены покупки', 'satınalma qiymətinin bölüşdürülməsi', 'ma', 'Bei der Kaufpreisallokation werden stille Reserven aufgedeckt.'],
  ['der Earn-out', 'earn-out', 'отсроченная доплата (earn-out)', 'earn-out (əlavə ödəniş)', 'ma', 'Ein Earn-out koppelt einen Teil des Preises an künftige Ergebnisse.'],
  ['das Pflichtangebot', 'mandatory offer', 'обязательное предложение', 'məcburi təklif', 'ma', 'Ab 30 Prozent der Stimmrechte muss ein Pflichtangebot abgegeben werden.'],
  ['der Minderheitsanteil', 'minority stake', 'миноритарная доля', 'azlıq payı', 'ma', 'Der Investor erwirbt einen Minderheitsanteil von 20 Prozent.'],
  ['die Mehrheitsbeteiligung', 'majority stake', 'мажоритарная доля', 'çoxluq payı', 'ma', 'Mit der Mehrheitsbeteiligung übernimmt er die Kontrolle.'],
  ['der Management-Buy-out', 'management buyout (MBO)', 'выкуп компании менеджментом', 'menecment tərəfindən satınalma', 'ma', 'Beim Management-Buy-out kauft die Geschäftsführung das Unternehmen.'],
  // ---- fin ----
  ['die Fremdfinanzierung', 'debt financing', 'долговое финансирование', 'borc maliyyələşdirməsi', 'fin', 'Die Fremdfinanzierung ist günstiger als Eigenkapital.'],
  ['die Eigenfinanzierung', 'equity financing', 'финансирование за счёт собственных средств', 'xüsusi vəsaitlə maliyyələşdirmə', 'fin', 'Bei der Eigenfinanzierung werden neue Aktien ausgegeben.'],
  ['das Darlehen', 'loan', 'заём, ссуда', 'borc (kredit)', 'fin', 'Das Darlehen hat eine Laufzeit von zehn Jahren.'],
  ['die Anleihe', 'bond', 'облигация', 'istiqraz (bond)', 'fin', 'Das Unternehmen hat eine Anleihe über 500 Millionen Euro begeben.'],
  ['die Tilgung', 'repayment', 'погашение', 'ödəniş (əsas borcun)', 'fin', 'Die Tilgung erfolgt in gleichen Raten.'],
  ['die Laufzeit', 'maturity, term', 'срок (займа)', 'müddət', 'fin', 'Die Laufzeit der Anleihe beträgt sieben Jahre.'],
  ['die Kreditlinie', 'credit line', 'кредитная линия', 'kredit xətti', 'fin', 'Die Kreditlinie wurde nicht in Anspruch genommen.'],
  ['der Konsortialkredit', 'syndicated loan', 'синдицированный кредит', 'sindikat krediti', 'fin', 'Mehrere Banken vergeben den Konsortialkredit gemeinsam.'],
  ['das Schuldscheindarlehen', 'Schuldschein loan', 'долговая расписка (Schuldschein)', 'Schuldschein krediti', 'fin', 'Ein Schuldscheindarlehen ist bei deutschen Mittelständlern beliebt.'],
  ['die Kreditbedingungen', 'covenants, loan terms', 'условия кредита (ковенанты)', 'kredit şərtləri (kovenantlar)', 'fin', 'Bei Verletzung der Kreditbedingungen kann die Bank kündigen.'],
  ['der Verschuldungsgrad', 'leverage ratio', 'уровень долговой нагрузки', 'borc yükü səviyyəsi', 'fin', 'Der Verschuldungsgrad liegt bei dem Dreifachen des EBITDA.'],
  ['die Zinsdeckung', 'interest coverage', 'покрытие процентов', 'faizlərin ödənilməsi əmsalı', 'fin', 'Die Zinsdeckung beträgt das Fünffache des EBIT.'],
  ['das Mezzanine-Kapital', 'mezzanine capital', 'мезонинный капитал', 'mezzanine kapital', 'fin', 'Mezzanine-Kapital liegt zwischen Eigen- und Fremdkapital.'],
  ['die nachrangige Schuld', 'subordinated debt', 'субординированный долг', 'subordinasiyalı borc', 'fin', 'Nachrangige Schuld wird im Insolvenzfall erst spät bedient.'],
  ['die Refinanzierung', 'refinancing', 'рефинансирование', 'yenidən maliyyələşdirmə', 'fin', 'Die Refinanzierung des Kredits steht im nächsten Jahr an.'],
  ['die Bonität', 'creditworthiness', 'кредитоспособность', 'kredit qabiliyyəti', 'fin', 'Die Bonität des Kunden wird laufend geprüft.'],
  ['der Kreditgeber', 'lender', 'кредитор (заимодавец)', 'kredit verən', 'fin', 'Der Kreditgeber verlangt Sicherheiten.'],
  ['der Kreditnehmer', 'borrower', 'заёмщик', 'borcalan', 'fin', 'Der Kreditnehmer zahlt vierteljährlich Zinsen.'],
  ['der Zinssatz', 'interest rate', 'процентная ставка', 'faiz dərəcəsi', 'fin', 'Der Zinssatz ist an den Euribor gekoppelt.'],
  // ---- mkt ----
  ['die Aktie', 'share, stock', 'акция', 'səhm', 'mkt', 'Die Aktie schloss mit einem Plus von zwei Prozent.'],
  ['die Börse', 'stock exchange', 'биржа', 'birja', 'mkt', 'Die Börse in Frankfurt ist die größte in Deutschland.'],
  ['der Kurs', 'price, share price', 'курс, котировка', 'məzənnə, kotirovka', 'mkt', 'Der Kurs fiel nach der Gewinnwarnung stark.'],
  ['die Dividende', 'dividend', 'дивиденд', 'dividend', 'mkt', 'Die Dividende wird einmal im Jahr gezahlt.'],
  ['die Rendite', 'yield, return', 'доходность', 'gəlirlilik', 'mkt', 'Die Rendite zehnjähriger Anleihen ist gestiegen.'],
  ['die Volatilität', 'volatility', 'волатильность', 'volatillik', 'mkt', 'Die Volatilität am Markt nahm zu.'],
  ['das Wertpapier', 'security', 'ценная бумага', 'qiymətli kağız', 'mkt', 'Aktien und Anleihen sind Wertpapiere.'],
  ['die Zentralbank', 'central bank', 'центральный банк', 'mərkəzi bank', 'mkt', 'Die Zentralbank steuert die Geldmenge über den Leitzins.'],
  ['der Leitzins', 'key interest rate', 'ключевая ставка', 'əsas faiz dərəcəsi', 'mkt', 'Die EZB hat den Leitzins erneut angehoben.'],
  ['die Geldpolitik', 'monetary policy', 'денежно-кредитная политика', 'pul siyasəti', 'mkt', 'Die Geldpolitik wirkt auf Kredite und Wechselkurse.'],
  ['die Inflation', 'inflation', 'инфляция', 'inflyasiya', 'mkt', 'Die Inflation lag im Oktober bei zwei Prozent.'],
  ['die Konjunktur', 'economic cycle, economy', 'конъюнктура, экономический цикл', 'konyunktura', 'mkt', 'Die Konjunktur in Deutschland schwächt sich ab.'],
  ['die Rezession', 'recession', 'рецессия', 'tənəzzül (resessiya)', 'mkt', 'Eine Rezession drückt die Gewinne der Unternehmen.'],
  ['der Kapitalmarkt', 'capital market', 'рынок капитала', 'kapital bazarı', 'mkt', 'Am Kapitalmarkt beschaffen sich Firmen langfristiges Geld.'],
  ['die Emission', 'issuance', 'эмиссия (выпуск)', 'emissiya', 'mkt', 'Die Emission der Anleihe war mehrfach überzeichnet.'],
  ['der Emittent', 'issuer', 'эмитент', 'emitent', 'mkt', 'Der Emittent zahlt jährlich einen festen Zins.'],
  ['die Platzierung', 'placement', 'размещение', 'yerləşdirmə', 'mkt', 'Die Platzierung der Aktien erfolgte bei institutionellen Anlegern.'],
  ['das Orderbuch', 'order book', 'книга заявок', 'sifariş kitabı', 'mkt', 'Das Orderbuch war schon am ersten Tag voll.'],
  ['der Anleger', 'investor', 'инвестор (частный)', 'investor (fərdi)', 'mkt', 'Viele Anleger verkauften ihre Aktien.'],
  ['der Handelsplatz', 'trading venue', 'торговая площадка', 'ticarət meydançası', 'mkt', 'Die Aktie wird an mehreren Handelsplätzen gehandelt.'],
  ['der Handelsumsatz', 'trading volume', 'объём торгов', 'ticarət həcmi', 'mkt', 'Der Handelsumsatz stieg auf ein Rekordniveau.'],
  ['der Kursgewinn', 'capital gain', 'курсовая прибыль', 'məzənnə qazancı', 'mkt', 'Der Kursgewinn ist steuerpflichtig.'],
  ['der Index', 'index', 'индекс', 'indeks', 'mkt', 'Der DAX ist der wichtigste deutsche Aktienindex.'],
]);
