'use strict';
// English version of the glossary: key -> [title, explanation, formula]
const GLOSS_EN = {
  ev: ['Enterprise Value (EV)', 'The value of the whole business for everyone who has put money into it: shareholders and lenders alike. It is what you would pay to buy the entire company together with its debt, while also getting its cash.', 'EV = Equity Value + Debt + Preferred + Minority − Cash'],
  eqv: ['Equity Value / Market Cap', 'The value of the company to shareholders only. For a public company this is the market capitalisation: the share price multiplied by the number of (diluted) shares.', 'Equity Value = share price × diluted shares'],
  tv: ['Terminal Value (TV)', 'The value of the company beyond the DCF forecast period. It is calculated as a single number at the end of the forecast and usually makes up 60-80% of the total valuation.', 'Gordon: TV = FCF × (1+g) / (WACC − g); or EBITDA × exit multiple'],
  dcf: ['DCF', 'Valuation based on discounted cash flows: forecast free cash flow for 5-10 years, add the Terminal Value and bring everything back to today at the WACC rate.', ''],
  mult: ['Multiple', 'The ratio of a company\'s value to one of its metrics (profit, revenue, book value). It lets you compare companies quickly: "for every euro of EBITDA the market pays 8 euros".', 'multiple = value / metric'],
  evebitda: ['EV/EBITDA', 'The most common multiple in M&A. It does not depend on debt, taxes or depreciation, so it compares the operating business of different companies well.', 'EV / EBITDA'],
  evrev: ['EV/Revenue', 'Business value divided by revenue. Used when there are no profits yet (technology, early growth).', 'EV / Revenue'],
  evebit: ['EV/EBIT', 'Business value divided by operating profit. It takes asset wear into account, so it is better than EV/EBITDA for capital-intensive companies.', 'EV / EBIT'],
  pe: ['P/E', 'Share price divided by earnings per share. Shows how much is paid for one unit of profit. It depends on debt, because Net Income is calculated after interest.', 'P/E = share price / EPS'],
  pb: ['P/B', 'Market capitalisation divided by book equity. The main multiple for banks and insurers.', 'P/B = Market Cap / Book Equity'],
  ptbv: ['P/TBV', 'Price to tangible book value (excluding goodwill and intangible assets). The main valuation metric for banks.', 'P/TBV = price / Tangible Book Value per share'],
  gordon: ['Gordon Growth', 'A way to calculate Terminal Value: we assume the cash flow grows forever at a small constant rate g. It only works if WACC is greater than g.', 'TV = FCF × (1+g) / (WACC − g)'],
  exitm: ['Exit Multiple', 'The second way to calculate Terminal Value: multiply the EBITDA of the last forecast year by the multiple at which we expect the company could be sold.', 'TV = EBITDA × multiple'],
  sotp: ['SOTP', 'Sum-of-the-Parts: value each business segment separately using its own multiples and add them up. Suitable for conglomerates.', ''],
  npv: ['NPV', 'Net present value: the sum of all future cash flows brought back to today, minus the initial investment. Above zero means the project creates value.', 'NPV = Σ CF/(1+r)^n − investment'],
  pv: ['PV', 'Present Value: today\'s value of a future sum. Money tomorrow is worth less than money today, so future amounts are divided by (1 + rate) to the power of the number of years.', 'PV = FV / (1 + r)^n'],
  ltm: ['LTM', 'Last Twelve Months: a metric for the past 12 months. It lets you compare companies between reports without waiting for the year end.', 'LTM = last year + current YTD − prior-year YTD'],
  ntm: ['NTM', 'Next Twelve Months: a forecast for the coming 12 months. The market looks forward, so NTM multiples are often more important than LTM.', ''],
  peg: ['PEG', 'P/E divided by the earnings growth rate. Helps compare an expensive fast-growing company with a cheap slow one. Around 1 is considered "fair".', 'PEG = P/E / EPS growth rate (%)'],
  tp: ['Target price', 'The target share price in an analyst report: what they think the stock will be worth in 12 months. Derived from a multiple or a DCF.', 'Upside = target price / price − 1'],
  upside: ['Upside', 'The potential rise of the share price to the target price, in percent.', 'Upside = target price / current price − 1'],
  ff: ['Football field', 'A chart with horizontal bars showing valuation ranges from different methods (DCF, comps, precedents, LBO). It shows the overall range of fair value.', ''],
  comps: ['Trading comps', 'Valuation using the multiples of similar public companies today. It does not include a control premium, so it is usually lower than precedent transactions.', ''],
  prec: ['Precedent transactions', 'Valuation using the multiples of past M&A deals with similar companies. It includes a control premium and synergies.', ''],
  disc: ['Discounting', 'Bringing future money back to today by dividing by (1 + rate) to the power of the number of years. The higher the rate and the longer the term, the lower today\'s value.', 'PV = FV / (1 + r)^n'],
  ro40: ['Rule of 40', 'A health rule for SaaS companies: revenue growth rate plus margin (more often FCF margin) should add up to at least 40%.', ''],
  wacc: ['WACC', 'Weighted average cost of capital: the minimum return a company must deliver to both shareholders and lenders. The discount rate for a DCF.', 'WACC = E/(D+E)×Re + D/(D+E)×Rd×(1−t)'],
  capm: ['CAPM', 'A model that calculates the required return on a stock: the risk-free rate plus beta multiplied by the market risk premium.', 'Re = Rf + β × (Rm − Rf)'],
  re: ['Cost of Equity (Re)', 'The return shareholders demand for the risk of investing in the company. Higher than the cost of debt, because shareholders get paid last.', 'Re = Rf + β × risk premium'],
  rd: ['Cost of Debt (Rd)', 'The rate at which the company borrows. In WACC it is taken after tax, because interest reduces taxable profit.', 'after tax: Rd × (1 − t)'],
  rf: ['Rf', 'The risk-free rate: the yield on government bonds of a reliable country (for example German Bunds). The basis for calculating the cost of capital.', ''],
  beta: ['Beta (β)', 'The sensitivity of a stock to market moves. β = 1 moves with the market, β > 1 moves more than the market (riskier), β < 1 moves less.', ''],
  nd: ['Net Debt', 'Net debt: all debt minus cash and cash equivalents. Shows how much the company really owes if it first repays debt with its cash.', 'Net Debt = Debt − Cash'],
  debt: ['Debt', 'Debt: bank loans, bonds, as well as leases under IFRS 16 and sometimes pension obligations.', ''],
  cash: ['Cash', 'Cash and cash equivalents. In the bridge from EV to Equity Value they are subtracted from EV: the buyer gets them together with the company, so the real price of the business is lower.', ''],
  pref: ['Preferred', 'Preferred shares: rank above ordinary shares in payouts and usually pay a fixed dividend. Counted as debt in EV.', ''],
  mi: ['Minority Interest', 'The share of minority shareholders in subsidiaries that are fully consolidated. It is added to EV because EBITDA includes 100% of their results.', ''],
  shield: ['Tax shield', 'Interest on debt is deducted from taxable profit, so debt is cheaper for the company: the real rate equals the rate × (1 − tax).', ''],
  dtl: ['DTL', 'Deferred tax liability: the tax in the accounts is higher than the tax actually paid now. It arises, for example, from accelerated tax depreciation or from revaluing assets in a deal.', ''],
  dta: ['DTA', 'Deferred tax asset: the tax payable is higher than the tax in the accounts. Example: tax losses from previous years that will reduce taxes in the future.', ''],
  lease: ['Lease liabilities', 'Lease obligations. Under IFRS 16 almost all leases appear on the balance sheet as debt, and the lease expense is replaced by depreciation and interest, so EBITDA goes up.', ''],
  ndebitda: ['Net Debt/EBITDA', 'The main measure of debt burden: how many years it would theoretically take the company to repay net debt out of its EBITDA. Above 4-5x is considered risky.', 'Net Debt / EBITDA'],
  tsm: ['TSM', 'Treasury Stock Method: a way to calculate dilution from options. In-the-money options create new shares, but the company "buys back" part of them with the exercise proceeds.', 'net new shares = options × (1 − strike / price)'],
  cov: ['Covenants', 'Conditions in a loan agreement. Maintenance covenants are tested regularly (for example Net Debt/EBITDA no higher than 4x), incurrence covenants are tested when new actions are taken.', ''],
  yc: ['Yield curve', 'A chart of bond yields against maturity. An inversion (short rates higher than long rates) has historically predicted a recession.', ''],
  ebitda: ['EBITDA', 'Earnings before interest, taxes, depreciation and amortisation. Shows operating profitability without the effect of capital structure. It is not the same as cash flow.', 'EBITDA = Revenue − COGS − OpEx (excl. D&A)'],
  ebit: ['EBIT', 'Operating profit: EBITDA minus depreciation and amortisation. It does not depend on debt or taxes.', 'EBIT = EBITDA − D&A'],
  ni: ['Net Income', 'Net profit: what is left for shareholders after interest and taxes.', 'NI = (EBIT − interest) × (1 − tax)'],
  rev: ['Revenue', 'Revenue: all the money earned from sales, before any costs are deducted.', ''],
  fcf: ['FCF', 'Free Cash Flow: the money left after operating costs, taxes and investment. This is what can be paid out to investors.', ''],
  ufcf: ['Unlevered FCF', 'Free cash flow before debt payments. It is available to all investors, so it is used in a DCF.', 'EBIT×(1−t) + D&A − CapEx − ΔNWC'],
  lfcf: ['Levered FCF', 'Free cash flow after interest and mandatory debt payments. It belongs to shareholders.', ''],
  nwc: ['Working Capital (NWC)', 'Working capital: operating current assets (receivables, inventory) minus operating current liabilities (payables). Growth in it absorbs cash, a decrease releases cash.', 'NWC = current assets − current liabilities (excl. cash and debt)'],
  capex: ['CapEx', 'Capital expenditure: money spent on equipment, buildings and other long-term assets. It does not reduce profit immediately, but turns into depreciation.', ''],
  da: ['D&A', 'Depreciation and amortisation: spreading the cost of assets over their useful life. A non-cash expense: it reduces profit but not cash.', ''],
  eps: ['EPS', 'Earnings per share: Net Income divided by the number of shares. The main metric for judging deals through accretion/dilution.', 'EPS = Net Income / number of shares'],
  nopat: ['NOPAT', 'Operating profit after tax but before interest. The basis for calculating free cash flow and ROIC.', 'NOPAT = EBIT × (1 − tax)'],
  roic: ['ROIC', 'Return on invested capital: how much profit the company earns on each euro invested in the business. A good business earns more than its capital costs.', 'ROIC = NOPAT / Invested Capital'],
  roe: ['ROE', 'Return on equity: how much net profit is earned on each euro of shareholder capital.', 'ROE = Net Income / Equity'],
  ffo: ['FFO', 'Funds From Operations: a profit measure for REITs. Net Income plus real estate depreciation minus gains on property sales.', ''],
  gp: ['Gross Profit', 'Gross profit: revenue minus the direct costs of production (COGS).', 'Gross Profit = Revenue − COGS'],
  gm: ['Gross Margin', 'Gross margin: the share of gross profit in revenue.', 'Gross Margin = Gross Profit / Revenue'],
  adj: ['Adjusted EBITDA', 'EBITDA excluding one-off items: restructuring, legal costs, impairments. Shows recurring profitability.', ''],
  re2: ['Retained Earnings', 'Retained earnings: accumulated profit that has stayed in the company. It grows with Net Income and falls with dividends.', 'RE = prior balance + NI − dividends'],
  ppe: ['PP&E', 'Property, plant and equipment: buildings, equipment, machinery. The main long-term asset of manufacturing companies.', ''],
  amort: ['Amortisation', 'Spreading the cost of a long-term asset over its useful life. A non-cash expense.', ''],
  margin: ['Margin', 'The share of profit in revenue, in percent. For example, an EBITDA margin of 20% means that out of every 100 euros of revenue, 20 euros remain as EBITDA.', ''],
  arr: ['ARR', 'Annual Recurring Revenue: yearly recurring revenue from subscriptions. The key metric for SaaS companies.', ''],
  dso: ['DSO', 'Days Sales Outstanding: how many days on average customers take to pay. The lower, the faster money comes back.', 'DSO = receivables / revenue × 365'],
  lbo: ['LBO', 'Leveraged Buyout: buying a company with a large share of borrowed money. The debt is repaid from the company\'s own cash flows, and after 3-7 years it is sold.', ''],
  ma: ['M&A', 'Mergers & Acquisitions. Investment banks advise on buying, selling and combining companies.', ''],
  accr: ['Accretive', 'A deal after which the acquirer\'s earnings per share (EPS) rises. In a stock deal this is usually the case if the acquirer\'s P/E is higher than the target\'s P/E.', ''],
  dil: ['Dilutive', 'A deal after which the acquirer\'s EPS falls. "Dilution" also means the watering down of shareholders\' stake when new shares are issued.', ''],
  moic: ['MOIC', 'Multiple on Invested Capital: how many times the invested money has grown. 2.0x means you invested 100 and got back 200.', 'MOIC = exit (equity) / entry (equity)'],
  irr: ['IRR', 'Internal Rate of Return: the average annual return on an investment taking time into account. It reflects that money received earlier is worth more.', 'IRR ≈ MOIC^(1/years) − 1'],
  gw: ['Goodwill', 'The difference between the purchase price of a company and the fair value of its identifiable net assets. It is not amortised, but is tested for impairment.', 'Goodwill = price − FV of net assets'],
  ipo: ['IPO', 'Initial public offering: a company sells shares to investors on an exchange for the first time. Banks organise the deal and charge a fee.', ''],
  cim: ['CIM', 'Confidential Information Memorandum: a detailed document about the company for potential buyers. The main marketing material of a sale.', ''],
  ioi: ['IOI', 'Indication of Interest: an informal, non-binding offer from a buyer in the first stage of a sale.', ''],
  spa: ['SPA', 'Share Purchase Agreement: the contract for the sale and purchase of shares. The main legal document of the deal.', ''],
  gs: ['Greenshoe', 'An option for the underwriter to place up to 15% additional shares in an IPO to stabilise the price after the placement.', ''],
  bf: ['Breakup fee', 'A fee paid by the target if it accepts a competing offer. It protects the first buyer.', ''],
  sweep: ['Cash sweep', 'Directing the company\'s free cash to early repayment of debt. The main way of deleveraging in an LBO.', ''],
  pik: ['PIK', 'Payment-in-kind: interest is not paid in cash but added to the principal of the debt. Cash stays in the company, but the debt grows.', ''],
  mac: ['MAC', 'Material Adverse Change: a clause that lets the buyer walk away from a deal if the target\'s position deteriorates materially.', ''],
  exit: ['Exit', 'Exit: the sale of a company or a stake by an investor to get the invested money back with a profit. For a sponsor usually in year 3-7.', ''],
  spons: ['Sponsor', 'Financial sponsor: a private equity fund that buys companies in an LBO.', ''],
  syn: ['Synergies', 'Additional value from combining companies. Cost synergies (cost savings) are more reliable than revenue synergies (cross-selling).', ''],
  cp: ['Control premium', 'A surcharge over the market share price that the buyer pays to gain control of the company. Usually 20-40%.', ''],
  delev: ['Deleveraging', 'Reducing the debt burden by repaying debt. One of the three sources of LBO returns.', ''],
  lock: ['Lock-up', 'A ban on insiders selling shares after an IPO for 90-180 days. It protects the price from selling pressure.', ''],
  earn: ['Earn-out', 'Part of the deal price that is paid later if the company reaches agreed results.', ''],
  book: ['Bookrunner', 'The bank that runs the order book and organises the placement of shares or bonds.', ''],
  uw: ['Underwriter', 'The bank that guarantees the placement of securities and takes on the risk of any unplaced portion.', ''],
  teaser: ['Teaser', 'A short anonymous one- or two-page overview of the company sent to potential buyers at the start of a sale.', ''],
  dr: ['Data room', 'A secure repository of company documents where serious buyers are admitted for checking (due diligence).', ''],
};
