'use strict';
// Deutsche Version des Glossars: Schlüssel -> [Titel, Erklärung, Formel]
window.GLOSS_DE = {
  ev: ['Enterprise Value (EV)', 'Der Wert des gesamten Unternehmens für alle, die darin investiert haben: Aktionäre und Kreditgeber. Es ist der Betrag, den man zahlen müsste, um das Unternehmen als Ganzes samt Schulden zu kaufen, dabei aber dessen Cash zu erhalten.', 'EV = Equity Value + Debt + Preferred + Minority − Cash'],
  eqv: ['Equity Value / Market Cap', 'Der Wert des Unternehmens nur für die Aktionäre. Bei einem börsennotierten Unternehmen ist das die Marktkapitalisierung: Aktienkurs mal Anzahl der (verwässerten) Aktien.', 'Equity Value = Aktienkurs × diluted shares'],
  tv: ['Terminal Value (TV)', 'Der Wert des Unternehmens jenseits des DCF-Prognosezeitraums. Er wird als eine einzige Zahl am Ende der Prognose berechnet und macht meist 60-80 % des gesamten Werts aus.', 'Gordon: TV = FCF × (1+g) / (WACC − g); oder EBITDA × Exit-Multiple'],
  dcf: ['DCF', 'Bewertung anhand abgezinster Cashflows: Man prognostiziert den Free Cashflow für 5-10 Jahre, addiert den Terminal Value und zinst alles mit dem WACC auf heute ab.', ''],
  mult: ['Multiple', 'Das Verhältnis des Unternehmenswerts zu einer Kennzahl (Gewinn, Umsatz, Buchwert). Es ermöglicht einen schnellen Vergleich: „Für jeden Euro EBITDA zahlt der Markt 8 Euro“.', 'Multiple = Wert / Kennzahl'],
  evebitda: ['EV/EBITDA', 'Das häufigste Multiple bei M&A. Es ist unabhängig von Schulden, Steuern und Abschreibungen und vergleicht daher das operative Geschäft verschiedener Unternehmen gut.', 'EV / EBITDA'],
  evrev: ['EV/Revenue', 'Unternehmenswert im Verhältnis zum Umsatz. Wird verwendet, wenn es noch keine Gewinne gibt (Technologie, frühes Wachstum).', 'EV / Revenue'],
  evebit: ['EV/EBIT', 'Unternehmenswert im Verhältnis zum operativen Gewinn. Es berücksichtigt den Verschleiß von Vermögenswerten und ist daher bei kapitalintensiven Unternehmen besser als EV/EBITDA.', 'EV / EBIT'],
  pe: ['P/E', 'Aktienkurs im Verhältnis zum Gewinn je Aktie. Zeigt, wie viel für eine Einheit Gewinn gezahlt wird. Es hängt von der Verschuldung ab, weil das Net Income nach Zinsen berechnet wird.', 'P/E = Aktienkurs / EPS'],
  pb: ['P/B', 'Marktkapitalisierung im Verhältnis zum buchmäßigen Eigenkapital. Das wichtigste Multiple für Banken und Versicherer.', 'P/B = Market Cap / Book Equity'],
  ptbv: ['P/TBV', 'Kurs im Verhältnis zum materiellen Buchwert des Eigenkapitals (ohne Goodwill und immaterielle Vermögenswerte). Die zentrale Kennzahl zur Bewertung von Banken.', 'P/TBV = Kurs / Tangible Book Value je Aktie'],
  gordon: ['Gordon Growth', 'Eine Methode zur Berechnung des Terminal Value: Wir nehmen an, dass der Cashflow ewig mit einer kleinen konstanten Rate g wächst. Funktioniert nur, wenn der WACC größer als g ist.', 'TV = FCF × (1+g) / (WACC − g)'],
  exitm: ['Exit Multiple', 'Die zweite Methode zur Berechnung des Terminal Value: Wir multiplizieren das EBITDA des letzten Prognosejahres mit dem Multiple, zu dem wir das Unternehmen voraussichtlich verkaufen könnten.', 'TV = EBITDA × Multiple'],
  sotp: ['SOTP', 'Sum-of-the-Parts: Jedes Geschäftssegment wird einzeln mit eigenen Multiples bewertet, und die Werte werden addiert. Geeignet für Konglomerate.', ''],
  npv: ['NPV', 'Kapitalwert: Die Summe aller künftigen Zahlungen, auf heute abgezinst, minus die Anfangsinvestition. Größer als null bedeutet, dass das Projekt Wert schafft.', 'NPV = Σ CF/(1+r)^n − Investition'],
  pv: ['PV', 'Present Value: der heutige Wert eines künftigen Betrags. Geld morgen ist weniger wert als Geld heute, deshalb werden künftige Beträge durch (1 + Zins) hoch Anzahl der Jahre geteilt.', 'PV = FV / (1 + r)^n'],
  ltm: ['LTM', 'Last Twelve Months: eine Kennzahl für die letzten 12 Monate. So lassen sich Unternehmen zwischen den Berichten vergleichen, ohne das Jahresende abzuwarten.', 'LTM = letztes Jahr + aktuelles YTD − YTD des Vorjahres'],
  ntm: ['NTM', 'Next Twelve Months: eine Prognose für die nächsten 12 Monate. Der Markt schaut nach vorn, deshalb sind NTM-Multiples oft wichtiger als LTM.', ''],
  peg: ['PEG', 'Das KGV (P/E) geteilt durch die Gewinnwachstumsrate. Hilft, ein teures, schnell wachsendes mit einem günstigen, langsamen Unternehmen zu vergleichen. Etwa 1 gilt als „fair“.', 'PEG = P/E / EPS-Wachstumsrate (%)'],
  tp: ['Target price', 'Der Kursziel-Wert in einem Analystenbericht: was die Aktie nach Einschätzung des Analysten in 12 Monaten wert ist. Wird über ein Multiple oder einen DCF berechnet.', 'Upside = Kursziel / Kurs − 1'],
  upside: ['Upside', 'Das Kurspotenzial der Aktie bis zum Kursziel, in Prozent.', 'Upside = Kursziel / aktueller Kurs − 1'],
  ff: ['Football field', 'Ein Diagramm mit horizontalen Balken der Bewertungsspannen verschiedener Methoden (DCF, Comps, Precedents, LBO). Es zeigt die Gesamtspanne des fairen Werts.', ''],
  comps: ['Trading comps', 'Bewertung anhand der heutigen Multiples vergleichbarer börsennotierter Unternehmen. Enthält keine Kontrollprämie und liegt daher meist unter den Precedent Transactions.', ''],
  prec: ['Precedent transactions', 'Bewertung anhand der Multiples früherer M&A-Transaktionen mit ähnlichen Unternehmen. Enthält Kontrollprämie und Synergien.', ''],
  disc: ['Abzinsung', 'Künftiges Geld wird auf heute zurückgerechnet, indem man durch (1 + Zins) hoch Anzahl der Jahre teilt. Je höher der Zins und je länger die Laufzeit, desto geringer der heutige Wert.', 'PV = FV / (1 + r)^n'],
  ro40: ['Rule of 40', 'Gesundheitsregel für SaaS-Unternehmen: Umsatzwachstum plus Marge (meist FCF-Marge) sollten mindestens 40 % ergeben.', ''],
  wacc: ['WACC', 'Gewichtete durchschnittliche Kapitalkosten: die Mindestrendite, die ein Unternehmen sowohl Aktionären als auch Kreditgebern bieten muss. Der Diskontierungssatz im DCF.', 'WACC = E/(D+E)×Re + D/(D+E)×Rd×(1−t)'],
  capm: ['CAPM', 'Ein Modell zur Berechnung der geforderten Aktienrendite: risikoloser Zins plus Beta mal Marktrisikoprämie.', 'Re = Rf + β × (Rm − Rf)'],
  re: ['Cost of Equity (Re)', 'Die Rendite, die Aktionäre für das Risiko der Investition in das Unternehmen verlangen. Höher als die Fremdkapitalkosten, weil Aktionäre als Letzte bezahlt werden.', 'Re = Rf + β × Risikoprämie'],
  rd: ['Cost of Debt (Rd)', 'Der Zinssatz, zu dem sich das Unternehmen Geld leiht. Im WACC wird er nach Steuern angesetzt, weil Zinsen den steuerpflichtigen Gewinn mindern.', 'nach Steuern: Rd × (1 − t)'],
  rf: ['Rf', 'Der risikolose Zins: die Rendite von Staatsanleihen eines zuverlässigen Landes (zum Beispiel deutsche Bunds). Grundlage zur Berechnung der Kapitalkosten.', ''],
  beta: ['Beta (β)', 'Die Sensitivität einer Aktie gegenüber Marktbewegungen. β = 1 bewegt sich wie der Markt, β > 1 stärker als der Markt (riskanter), β < 1 schwächer.', ''],
  nd: ['Net Debt', 'Nettoverschuldung: alle Schulden minus Cash und Cash-Äquivalente. Zeigt, wie viel das Unternehmen tatsächlich schuldet, wenn es zuerst Schulden mit seinem Cash tilgt.', 'Net Debt = Debt − Cash'],
  debt: ['Debt', 'Schulden: Bankkredite, Anleihen sowie Leasing nach IFRS 16 und manchmal Pensionsverpflichtungen.', ''],
  cash: ['Cash', 'Zahlungsmittel und Zahlungsmitteläquivalente. In der Brücke von EV zu Equity Value werden sie vom EV abgezogen: Der Käufer erhält sie mit dem Unternehmen, der reale Preis des Geschäfts ist daher niedriger.', ''],
  pref: ['Preferred', 'Vorzugsaktien: Sie stehen bei Ausschüttungen vor den Stammaktien und zahlen meist eine feste Dividende. Im EV werden sie wie Schulden behandelt.', ''],
  mi: ['Minority Interest', 'Der Anteil von Minderheitsaktionären an voll konsolidierten Tochtergesellschaften. Er wird zum EV addiert, weil das EBITDA 100 % von deren Ergebnis enthält.', ''],
  shield: ['Steuerschild (tax shield)', 'Schuldzinsen werden vom steuerpflichtigen Gewinn abgezogen, deshalb ist Fremdkapital für das Unternehmen günstiger: Der reale Zins entspricht dem Zins × (1 − Steuer).', ''],
  dtl: ['DTL', 'Latente Steuerverbindlichkeit: Die Steuer im Abschluss ist höher als die aktuell tatsächlich gezahlte Steuer. Entsteht zum Beispiel durch beschleunigte steuerliche Abschreibung oder Aufwertung von Vermögenswerten bei einer Transaktion.', ''],
  dta: ['DTA', 'Latenter Steueranspruch: Die zu zahlende Steuer ist höher als die Steuer im Abschluss. Beispiel: steuerliche Verlustvorträge aus früheren Jahren, die künftig die Steuern senken.', ''],
  lease: ['Lease liabilities', 'Leasingverbindlichkeiten. Nach IFRS 16 erscheint fast jedes Leasing als Schuld in der Bilanz, und der Aufwand wird durch Abschreibung und Zinsen ersetzt, deshalb steigt das EBITDA.', ''],
  ndebitda: ['Net Debt/EBITDA', 'Die wichtigste Kennzahl für die Schuldenlast: in wie vielen Jahren das Unternehmen die Nettoverschuldung theoretisch aus seinem EBITDA tilgen könnte. Über 4-5x gilt als riskant.', 'Net Debt / EBITDA'],
  tsm: ['TSM', 'Treasury Stock Method: eine Methode zur Berechnung der Verwässerung durch Optionen. Optionen im Geld erzeugen neue Aktien, doch das Unternehmen „kauft“ einen Teil mit dem Ausübungserlös zurück.', 'neue Netto-Aktien = Optionen × (1 − Strike / Kurs)'],
  cov: ['Covenants', 'Bedingungen in einem Kreditvertrag. Maintenance Covenants werden regelmäßig geprüft (z. B. Net Debt/EBITDA nicht höher als 4x), Incurrence Covenants bei neuen Handlungen.', ''],
  yc: ['Zinskurve', 'Ein Diagramm der Anleiherenditen nach Laufzeit. Eine Inversion (kurze Zinsen höher als lange) hat historisch eine Rezession angekündigt.', ''],
  ebitda: ['EBITDA', 'Gewinn vor Zinsen, Steuern und Abschreibungen. Zeigt die operative Profitabilität ohne Einfluss der Kapitalstruktur. Entspricht nicht dem Cashflow.', 'EBITDA = Revenue − COGS − OpEx (ohne D&A)'],
  ebit: ['EBIT', 'Operativer Gewinn: EBITDA minus Abschreibungen. Unabhängig von Schulden und Steuern.', 'EBIT = EBITDA − D&A'],
  ni: ['Net Income', 'Jahresüberschuss: was nach Zinsen und Steuern für die Aktionäre übrig bleibt.', 'NI = (EBIT − Zinsen) × (1 − Steuer)'],
  rev: ['Revenue', 'Umsatz: alles Geld aus Verkäufen, vor Abzug jeglicher Kosten.', ''],
  fcf: ['FCF', 'Free Cashflow: das Geld, das nach operativen Kosten, Steuern und Investitionen übrig bleibt. Genau das kann an Investoren ausgeschüttet werden.', ''],
  ufcf: ['Unlevered FCF', 'Free Cashflow vor Schuldendienst. Er steht allen Investoren zur Verfügung und wird daher im DCF verwendet.', 'EBIT×(1−t) + D&A − CapEx − ΔNWC'],
  lfcf: ['Levered FCF', 'Free Cashflow nach Zinsen und verpflichtenden Tilgungen. Er gehört den Aktionären.', ''],
  nwc: ['Working Capital (NWC)', 'Betriebskapital: operatives Umlaufvermögen (Forderungen, Vorräte) minus operative kurzfristige Verbindlichkeiten (Lieferantenschulden). Wachstum bindet Cash, ein Rückgang setzt Cash frei.', 'NWC = Umlaufvermögen − kurzfristige Verbindlichkeiten (ohne Cash und Schulden)'],
  capex: ['CapEx', 'Investitionsausgaben: Geld für Anlagen, Gebäude und andere langfristige Vermögenswerte. Sie mindern den Gewinn nicht sofort, sondern werden zu Abschreibungen.', ''],
  da: ['D&A', 'Abschreibungen: Verteilung der Anschaffungskosten von Vermögenswerten auf ihre Nutzungsdauer. Ein nicht zahlungswirksamer Aufwand: Er mindert den Gewinn, nicht aber das Cash.', ''],
  eps: ['EPS', 'Gewinn je Aktie: Net Income geteilt durch die Aktienanzahl. Die wichtigste Kennzahl zur Beurteilung von Deals über Accretion/Dilution.', 'EPS = Net Income / Aktienanzahl'],
  nopat: ['NOPAT', 'Operativer Gewinn nach Steuern, aber vor Zinsen. Grundlage für die Berechnung des Free Cashflow und des ROIC.', 'NOPAT = EBIT × (1 − Steuer)'],
  roic: ['ROIC', 'Rendite auf das investierte Kapital: wie viel Gewinn das Unternehmen auf jeden in das Geschäft investierten Euro erzielt. Ein gutes Geschäft verdient mehr, als das Kapital kostet.', 'ROIC = NOPAT / Invested Capital'],
  roe: ['ROE', 'Eigenkapitalrendite: wie viel Jahresüberschuss auf jeden Euro Eigenkapital entfällt.', 'ROE = Net Income / Equity'],
  ffo: ['FFO', 'Funds From Operations: eine Gewinnkennzahl für REITs. Net Income plus Abschreibungen auf Immobilien minus Gewinne aus Immobilienverkäufen.', ''],
  gp: ['Gross Profit', 'Rohertrag: Umsatz minus direkte Herstellungskosten (COGS).', 'Gross Profit = Revenue − COGS'],
  gm: ['Gross Margin', 'Rohertragsmarge: der Anteil des Rohertrags am Umsatz.', 'Gross Margin = Gross Profit / Revenue'],
  adj: ['Adjusted EBITDA', 'EBITDA ohne Einmalposten: Restrukturierung, Rechtskosten, Wertminderungen. Zeigt die wiederkehrende Profitabilität.', ''],
  re2: ['Retained Earnings', 'Gewinnrücklagen: angesammelter Gewinn, der im Unternehmen geblieben ist. Wächst mit dem Net Income und sinkt durch Dividenden.', 'RE = Vorjahresbestand + NI − Dividenden'],
  ppe: ['PP&E', 'Sachanlagen: Gebäude, Ausrüstung, Maschinen. Das wichtigste langfristige Vermögen von Produktionsunternehmen.', ''],
  amort: ['Amortisation', 'Verteilung der Anschaffungskosten eines langfristigen Vermögenswerts auf seine Nutzungsdauer. Ein nicht zahlungswirksamer Aufwand.', ''],
  margin: ['Marge', 'Der Gewinnanteil am Umsatz in Prozent. Eine EBITDA-Marge von 20 % bedeutet zum Beispiel, dass von je 100 Euro Umsatz 20 Euro EBITDA übrig bleiben.', ''],
  arr: ['ARR', 'Annual Recurring Revenue: jährlich wiederkehrender Umsatz aus Abonnements. Die Schlüsselkennzahl von SaaS-Unternehmen.', ''],
  dso: ['DSO', 'Days Sales Outstanding: nach wie vielen Tagen Kunden im Durchschnitt zahlen. Je kleiner, desto schneller fließt das Geld zurück.', 'DSO = Forderungen / Umsatz × 365'],
  lbo: ['LBO', 'Leveraged Buyout: Übernahme eines Unternehmens mit hohem Fremdkapitalanteil. Die Schulden werden aus den Cashflows des Unternehmens selbst getilgt, und nach 3-7 Jahren wird es verkauft.', ''],
  ma: ['M&A', 'Mergers & Acquisitions: Fusionen und Übernahmen. Investmentbanken beraten beim Kauf, Verkauf und Zusammenschluss von Unternehmen.', ''],
  accr: ['Accretive', 'Ein Deal, nach dem der Gewinn je Aktie (EPS) des Käufers steigt. Bei Zahlung in Aktien ist das meist der Fall, wenn das KGV des Käufers höher ist als das des Ziels.', ''],
  dil: ['Dilutive', 'Ein Deal, nach dem das EPS des Käufers sinkt. „Dilution“ bedeutet auch die Verwässerung des Anteils der Aktionäre bei der Ausgabe neuer Aktien.', ''],
  moic: ['MOIC', 'Multiple on Invested Capital: um das Wievielfache das investierte Geld gewachsen ist. 2,0x bedeutet: 100 investiert, 200 erhalten.', 'MOIC = Exit (Equity) / Einstieg (Equity)'],
  irr: ['IRR', 'Internal Rate of Return: die durchschnittliche jährliche Rendite einer Investition unter Berücksichtigung der Zeit. Sie bildet ab, dass früher erhaltenes Geld mehr wert ist.', 'IRR ≈ MOIC^(1/Jahre) − 1'],
  gw: ['Goodwill', 'Der Unterschied zwischen dem Kaufpreis eines Unternehmens und dem beizulegenden Zeitwert seiner identifizierbaren Nettovermögenswerte. Wird nicht abgeschrieben, aber auf Wertminderung geprüft.', 'Goodwill = Preis − FV des Nettovermögens'],
  ipo: ['IPO', 'Initial Public Offering: Ein Unternehmen verkauft erstmals Aktien an Investoren an der Börse. Banken organisieren den Deal und erhalten eine Provision.', ''],
  cim: ['CIM', 'Confidential Information Memorandum: ein ausführliches Dokument über das Unternehmen für potenzielle Käufer. Das wichtigste Marketingmaterial eines Verkaufs.', ''],
  ioi: ['IOI', 'Indication of Interest: ein informelles, unverbindliches Angebot eines Käufers in der ersten Phase eines Verkaufs.', ''],
  spa: ['SPA', 'Share Purchase Agreement: der Kaufvertrag über Aktien. Das wichtigste Rechtsdokument des Deals.', ''],
  gs: ['Greenshoe', 'Eine Option des Underwriters, bei einem IPO bis zu 15 % zusätzliche Aktien zu platzieren, um den Kurs nach der Platzierung zu stabilisieren.', ''],
  bf: ['Breakup fee', 'Eine Gebühr, die das Zielunternehmen zahlt, wenn es ein konkurrierendes Angebot annimmt. Schützt den ersten Käufer.', ''],
  sweep: ['Cash sweep', 'Freies Cash des Unternehmens wird zur vorzeitigen Schuldentilgung verwendet. Der wichtigste Weg zum Delevering im LBO.', ''],
  pik: ['PIK', 'Payment-in-kind: Zinsen werden nicht in bar gezahlt, sondern zur Schuld addiert. Das Cash bleibt im Unternehmen, aber die Schuld wächst.', ''],
  mac: ['MAC', 'Material Adverse Change: eine Klausel, die dem Käufer erlaubt, vom Deal zurückzutreten, wenn sich die Lage des Ziels wesentlich verschlechtert.', ''],
  exit: ['Exit', 'Ausstieg: Verkauf eines Unternehmens oder Anteils durch einen Investor, um das investierte Geld samt Gewinn zurückzuholen. Für einen Sponsor meist im 3.-7. Jahr.', ''],
  spons: ['Sponsor', 'Finanzinvestor: ein Private-Equity-Fonds, der Unternehmen in einem LBO kauft.', ''],
  syn: ['Synergien', 'Zusätzlicher Wert aus dem Zusammenschluss von Unternehmen. Kostensynergien (Kosteneinsparungen) sind verlässlicher als Umsatzsynergien (Cross-Selling).', ''],
  cp: ['Kontrollprämie', 'Ein Aufschlag auf den Marktkurs der Aktie, den der Käufer für die Kontrolle über das Unternehmen zahlt. Meist 20-40 %.', ''],
  delev: ['Deleveraging', 'Abbau der Schuldenlast durch Tilgung. Eine der drei Renditequellen im LBO.', ''],
  lock: ['Lock-up', 'Ein Verkaufsverbot für Insider nach dem IPO für 90-180 Tage. Schützt den Kurs vor Verkaufsdruck.', ''],
  earn: ['Earn-out', 'Ein Teil des Kaufpreises, der später gezahlt wird, wenn das Unternehmen vereinbarte Ergebnisse erreicht.', ''],
  book: ['Bookrunner', 'Die Bank, die das Orderbuch führt und die Platzierung von Aktien oder Anleihen organisiert.', ''],
  uw: ['Underwriter', 'Die Bank, die die Platzierung von Wertpapieren garantiert und das Risiko des nicht platzierten Teils übernimmt.', ''],
  teaser: ['Teaser', 'Ein kurzer anonymer Überblick über das Unternehmen auf ein bis zwei Seiten, der zu Beginn eines Verkaufs an potenzielle Käufer verschickt wird.', ''],
  dr: ['Data room', 'Ein geschütztes Archiv mit Unternehmensdokumenten, zu dem ernsthafte Käufer zur Prüfung (Due Diligence) zugelassen werden.', ''],
};
