'use strict';
// Lüğətin Azərbaycan versiyası: açar -> [başlıq, izah, düstur]
window.GLOSS_AZ = {
  ev: ['Enterprise Value (EV)', 'Bütün biznesin ona pul qoyan hər kəs üçün dəyəri: həm səhmdarlar, həm də kreditorlar. Şirkəti borcları ilə birlikdə tam almaq, lakin onun pulunu da əldə etmək üçün ödəməli olacağınız məbləğdir.', 'EV = Equity Value + Debt + Preferred + Minority − Cash'],
  eqv: ['Equity Value / Market Cap', 'Şirkətin yalnız səhmdarlar üçün dəyəri. Açıq şirkətdə bu, bazar kapitallaşmasıdır: səhmin qiyməti vurulsun (diluted) səhmlərin sayına.', 'Equity Value = səhmin qiyməti × diluted shares'],
  tv: ['Terminal Value (TV)', 'DCF proqnoz dövründən kənarda şirkətin dəyəri. Proqnozun sonunda tək bir rəqəmlə hesablanır və adətən ümumi qiymətləndirmənin 60-80%-ni verir.', 'Gordon: TV = FCF × (1+g) / (WACC − g); və ya EBITDA × exit multiple'],
  dcf: ['DCF', 'Diskontlaşdırılmış pul axınları üzrə qiymətləndirmə: 5-10 il üçün sərbəst pul axınını proqnozlaşdırırıq, Terminal Value əlavə edirik və hər şeyi WACC dərəcəsi ilə bu günə gətiririk.', ''],
  mult: ['Mültiplikator', 'Şirkətin dəyərinin onun göstəricisinə (mənfəət, gəlir, balans kapitalı) nisbəti. Şirkətləri tez müqayisə etməyə imkan verir: «hər avro EBITDA üçün bazar 8 avro ödəyir».', 'mültiplikator = dəyər / göstərici'],
  evebitda: ['EV/EBITDA', 'M&A-da ən tez-tez işlənən mültiplikator. Borcdan, vergilərdən və amortizasiyadan asılı deyil, buna görə müxtəlif şirkətlərin əməliyyat biznesini yaxşı müqayisə edir.', 'EV / EBITDA'],
  evrev: ['EV/Revenue', 'Biznesin dəyərinin gəlirə nisbəti. Hələ mənfəət olmadıqda tətbiq olunur (texnologiya, erkən artım).', 'EV / Revenue'],
  evebit: ['EV/EBIT', 'Biznesin dəyərinin əməliyyat mənfəətinə nisbəti. Aktivlərin köhnəlməsini nəzərə alır, buna görə kapital tutumlu şirkətlər üçün EV/EBITDA-dan yaxşıdır.', 'EV / EBIT'],
  pe: ['P/E', 'Səhmin qiymətinin bir səhmə düşən mənfəətə nisbəti. Bir vahid mənfəət üçün nə qədər ödənildiyini göstərir. Borcdan asılıdır, çünki Net Income faizlərdən sonra hesablanır.', 'P/E = səhmin qiyməti / EPS'],
  pb: ['P/B', 'Bazar kapitallaşmasının balans kapitalına nisbəti. Banklar və sığortaçılar üçün əsas mültiplikator.', 'P/B = Market Cap / Book Equity'],
  ptbv: ['P/TBV', 'Qiymətin maddi balans kapitalına (goodwill və qeyri-maddi aktivlər olmadan) nisbəti. Bankların qiymətləndirilməsinin əsas göstəricisi.', 'P/TBV = qiymət / bir səhmə Tangible Book Value'],
  gordon: ['Gordon Growth', 'Terminal Value-nu hesablamaq üsulu: pul axınının əbədi olaraq kiçik sabit g tempi ilə artdığını fərz edirik. Yalnız WACC g-dən böyük olduqda işləyir.', 'TV = FCF × (1+g) / (WACC − g)'],
  exitm: ['Exit Multiple', 'Terminal Value-nu hesablamağın ikinci üsulu: proqnozun son ilinin EBITDA-sını şirkəti satmaq olacağını gözlədiyimiz mültiplikatora vururuq.', 'TV = EBITDA × mültiplikator'],
  sotp: ['SOTP', 'Sum-of-the-Parts: hər biznes seqmentini öz mültiplikatorları ilə ayrıca qiymətləndirib toplayırıq. Konqlomeratlar üçün uyğundur.', ''],
  npv: ['NPV', 'Xalis cari dəyər: bütün gələcək axınların bu günə gətirilmiş cəmi minus ilkin investisiya. Sıfırdan böyük olması layihənin dəyər yaratdığını bildirir.', 'NPV = Σ CF/(1+r)^n − investisiya'],
  pv: ['PV', 'Present Value: gələcək məbləğin bugünkü dəyəri. Sabahkı pul bugünkündən az dəyərlidir, ona görə də gələcək məbləğlər (1 + faiz) vurulsun illərin sayı qüvvətinə bölünür.', 'PV = FV / (1 + r)^n'],
  ltm: ['LTM', 'Last Twelve Months: son 12 ay üzrə göstərici. İlin sonunu gözləmədən şirkətləri hesabatlar arasında müqayisə etməyə imkan verir.', 'LTM = son il + cari YTD − keçən ilin YTD-si'],
  ntm: ['NTM', 'Next Twelve Months: növbəti 12 ay üçün proqnoz. Bazar irəliyə baxır, buna görə NTM üzrə mültiplikatorlar tez-tez LTM-dən vacibdir.', ''],
  peg: ['PEG', 'P/E-nin mənfəət artımı tempinə bölünməsi. Bahalı sürətlə böyüyən şirkəti ucuz yavaş şirkətlə müqayisə etməyə kömək edir. Təxminən 1 «ədalətli» sayılır.', 'PEG = P/E / EPS artım tempi (%)'],
  tp: ['Target price', 'Analitik hesabatında səhmin hədəf qiyməti: onun 12 aydan sonra səhmi nə qədər qiymətləndirdiyi. Mültiplikator və ya DCF vasitəsilə hesablanır.', 'Upside = target price / qiymət − 1'],
  upside: ['Upside', 'Səhmin qiymətinin hədəf qiymətə qədər artım potensialı, faizlə.', 'Upside = target price / cari qiymət − 1'],
  ff: ['Football field', 'Müxtəlif metodlar (DCF, comps, precedents, LBO) üzrə qiymətləndirmə diapazonlarının üfüqi zolaqlarla göstərildiyi qrafik. Ədalətli dəyərin ümumi diapazonunu göstərir.', ''],
  comps: ['Trading comps', 'Bu gün oxşar açıq şirkətlərin mültiplikatorları üzrə qiymətləndirmə. Nəzarət premiyasını daxil etmir, buna görə adətən precedent transactions-dan aşağı olur.', ''],
  prec: ['Precedent transactions', 'Oxşar şirkətlərlə keçmiş M&A sövdələşmələrinin mültiplikatorları üzrə qiymətləndirmə. Nəzarət premiyasını və sinerjiləri daxil edir.', ''],
  disc: ['Diskontlaşdırma', 'Gələcək pulun (1 + faiz) illərin sayı qüvvətinə bölünməklə bu günə gətirilməsi. Faiz nə qədər yüksək və müddət nə qədər uzaqdırsa, bugünkü dəyər bir o qədər azdır.', 'PV = FV / (1 + r)^n'],
  ro40: ['Rule of 40', 'SaaS şirkətinin sağlamlıq qaydası: gəlir artım tempi üstəgəl marja (daha çox FCF marjası) ən azı 40% verməlidir.', ''],
  wacc: ['WACC', 'Kapitalın orta çəkili dəyəri: şirkətin həm səhmdarlara, həm də kreditorlara verməli olduğu minimum gəlirlilik. DCF üçün diskont dərəcəsi.', 'WACC = E/(D+E)×Re + D/(D+E)×Rd×(1−t)'],
  capm: ['CAPM', 'Səhmlərin tələb olunan gəlirliliyini hesablayan model: risksiz faiz üstəgəl beta vurulsun bazar riski premiyasına.', 'Re = Rf + β × (Rm − Rf)'],
  re: ['Cost of Equity (Re)', 'Səhmdarların şirkətə investisiya riskinə görə tələb etdiyi gəlirlilik. Borcun dəyərindən yüksəkdir, çünki səhmdarlar pulu sonuncu alırlar.', 'Re = Rf + β × risk premiyası'],
  rd: ['Cost of Debt (Rd)', 'Şirkətin pul borc aldığı faiz dərəcəsi. WACC-da vergidən sonra götürülür, çünki faizlər vergiyə cəlb olunan mənfəəti azaldır.', 'vergidən sonra: Rd × (1 − t)'],
  rf: ['Rf', 'Risksiz dərəcə: etibarlı ölkənin dövlət istiqrazlarının gəlirliliyi (məsələn, Alman Bund-ları). Kapital dəyərinin hesablanması üçün əsasdır.', ''],
  beta: ['Beta (β)', 'Səhmin bazar hərəkətinə həssaslığı. β = 1 bazar kimi hərəkət edir, β > 1 bazardan güclü (daha riskli), β < 1 daha zəif.', ''],
  nd: ['Net Debt', 'Xalis borc: bütün borc minus nağd pul və onun ekvivalentləri. Şirkət əvvəlcə borcu öz pulu ilə ödəsə, əslində nə qədər borclu olduğunu göstərir.', 'Net Debt = Debt − Cash'],
  debt: ['Debt', 'Borc: bank kreditləri, istiqrazlar, həmçinin IFRS 16 üzrə icarə və bəzən pensiya öhdəlikləri.', ''],
  cash: ['Cash', 'Nağd pul və onun ekvivalentləri. EV-dən Equity Value-ya körpüdə onlar EV-dən çıxılır: alıcı onları şirkətlə birlikdə alır, buna görə biznesin real qiyməti daha aşağıdır.', ''],
  pref: ['Preferred', 'İmtiyazlı səhmlər: ödəniş prioritetinə görə adi səhmlərdən yuxarıdır və adətən sabit dividend verir. EV-də borc kimi nəzərə alınır.', ''],
  mi: ['Minority Interest', 'Tam konsolidasiya olunan törəmə şirkətlərdə azlıq səhmdarlarının payı. EV-yə əlavə olunur, çünki EBITDA onların nəticəsinin 100%-ni daxil edir.', ''],
  shield: ['Vergi qalxanı (tax shield)', 'Borc üzrə faizlər vergiyə cəlb olunan mənfəətdən çıxılır, buna görə borc şirkət üçün daha ucuzdur: real dərəcə dərəcə × (1 − vergi)-ə bərabərdir.', ''],
  dtl: ['DTL', 'Təxirə salınmış vergi öhdəliyi: hesabatdakı vergi hazırda real ödənilən vergidən yüksəkdir. Məsələn, sürətləndirilmiş vergi amortizasiyası və ya sövdələşmədə aktivlərin yenidən qiymətləndirilməsi zamanı yaranır.', ''],
  dta: ['DTA', 'Təxirə salınmış vergi aktivi: ödənilməli vergi hesabatdakı vergidən yüksəkdir. Nümunə: keçmiş illərin vergi zərərləri, gələcəkdə vergiləri azaldacaq.', ''],
  lease: ['Lease liabilities', 'İcarə öhdəlikləri. IFRS 16-ya görə demək olar ki, bütün icarə balansda borc kimi əks olunur, onun üzrə xərc isə amortizasiya və faizlərlə əvəz olunur, buna görə EBITDA artır.', ''],
  ndebitda: ['Net Debt/EBITDA', 'Borc yükünün əsas göstəricisi: şirkətin xalis borcu nəzəri olaraq öz EBITDA-sı hesabına neçə ilə ödəyəcəyi. 4-5x-dən yuxarı riskli sayılır.', 'Net Debt / EBITDA'],
  tsm: ['TSM', 'Treasury Stock Method: opsionlardan durulmanı hesablamaq üsulu. Sərfəli strike-lı opsionlar yeni səhmlər verir, lakin şirkət icra gəlirləri hesabına onun bir hissəsini «geri alır».', 'xalis yeni səhmlər = opsionlar × (1 − strike / qiymət)'],
  cov: ['Kovenantlar', 'Kredit müqaviləsindəki şərtlər. Maintenance kovenantlar müntəzəm yoxlanılır (məsələn, Net Debt/EBITDA 4x-dən yuxarı olmasın), incurrence kovenantlar yeni addımlar zamanı yoxlanılır.', ''],
  yc: ['Gəlirlilik əyrisi', 'İstiqrazların gəlirliliyinin müddətdən asılılıq qrafiki. İnversiya (qısa dərəcələr uzunlardan yüksək) tarixən tənəzzülü xəbər vermişdir.', ''],
  ebitda: ['EBITDA', 'Faizlər, vergilər və amortizasiyadan əvvəlki mənfəət. Kapital strukturunun təsiri olmadan əməliyyat mənfəətliliyini göstərir. Pul axınına bərabər deyil.', 'EBITDA = Revenue − COGS − OpEx (D&A olmadan)'],
  ebit: ['EBIT', 'Əməliyyat mənfəəti: EBITDA minus amortizasiya. Borcdan və vergilərdən asılı deyil.', 'EBIT = EBITDA − D&A'],
  ni: ['Net Income', 'Xalis mənfəət: faizlər və vergilərdən sonra səhmdarlara qalan hissə.', 'NI = (EBIT − faizlər) × (1 − vergi)'],
  rev: ['Revenue', 'Gəlir: satışdan qazanılmış bütün pul, hər hansı xərclər çıxılmazdan əvvəl.', ''],
  fcf: ['FCF', 'Free Cash Flow: əməliyyat xərcləri, vergilər və investisiyalardan sonra qalan pul. Məhz onu investorlara ödəmək olar.', ''],
  ufcf: ['Unlevered FCF', 'Borc üzrə ödənişlərdən əvvəlki sərbəst pul axını. Bütün investorlar üçün əlçatandır, buna görə DCF-də istifadə olunur.', 'EBIT×(1−t) + D&A − CapEx − ΔNWC'],
  lfcf: ['Levered FCF', 'Faizlər və məcburi borc ödənişlərindən sonrakı sərbəst pul axını. Səhmdarlara məxsusdur.', ''],
  nwc: ['Working Capital (NWC)', 'Dövriyyə kapitalı: əməliyyat cari aktivləri (debitor borcları, ehtiyatlar) minus əməliyyat cari öhdəlikləri (kreditor borcları). Artımı pul aparır, azalması pulu azad edir.', 'NWC = cari aktivlər − cari öhdəliklər (cash və borc olmadan)'],
  capex: ['CapEx', 'Kapital xərcləri: avadanlıq, binalar və digər uzunmüddətli aktivlərə xərclənmiş pul. Mənfəəti dərhal azaltmır, amortizasiyaya çevrilir.', ''],
  da: ['D&A', 'Amortizasiya: aktivlərin dəyərinin xidmət illəri üzrə bölüşdürülməsi. Pulsuz xərcdir: mənfəəti azaldır, pulu azaltmır.', ''],
  eps: ['EPS', 'Bir səhmə düşən mənfəət: Net Income səhmlərin sayına bölünür. Accretion/dilution vasitəsilə sövdələşmələri qiymətləndirmək üçün əsas göstərici.', 'EPS = Net Income / səhmlərin sayı'],
  nopat: ['NOPAT', 'Vergidən sonra, lakin faizlərdən əvvəl əməliyyat mənfəəti. Sərbəst axın və ROIC hesablamaq üçün baza.', 'NOPAT = EBIT × (1 − vergi)'],
  roic: ['ROIC', 'İnvestisiya olunmuş kapitalın gəlirliliyi: şirkətin bizneslə bağlı hər avro üçün nə qədər mənfəət qazandığı. Yaxşı biznes kapitalın dəyərindən çox qazanır.', 'ROIC = NOPAT / Invested Capital'],
  roe: ['ROE', 'Xüsusi kapitalın gəlirliliyi: səhmdar kapitalının hər avrosuna nə qədər xalis mənfəət düşür.', 'ROE = Net Income / Equity'],
  ffo: ['FFO', 'Funds From Operations: REIT üçün mənfəət göstəricisi. Net Income üstəgəl daşınmaz əmlakın amortizasiyası minus obyektlərin satışından mənfəət.', ''],
  gp: ['Gross Profit', 'Ümumi mənfəət: gəlir minus istehsalın birbaşa xərcləri (COGS).', 'Gross Profit = Revenue − COGS'],
  gm: ['Gross Margin', 'Ümumi marja: ümumi mənfəətin gəlirdəki payı.', 'Gross Margin = Gross Profit / Revenue'],
  adj: ['Adjusted EBITDA', 'Birdəfəlik maddələr olmadan EBITDA: restrukturizasiya, məhkəmə xərcləri, dəyərsizləşmə. Təkrarlanan mənfəətliliyi göstərir.', ''],
  re2: ['Retained Earnings', 'Bölüşdürülməmiş mənfəət: şirkətdə qalmış yığılmış mənfəət. Net Income ilə artır, dividendlərlə azalır.', 'RE = əvvəlki qalıq + NI − dividendlər'],
  ppe: ['PP&E', 'Əsas vəsaitlər: binalar, avadanlıq, maşınlar. İstehsal şirkətlərinin əsas uzunmüddətli aktivi.', ''],
  amort: ['Amortizasiya', 'Uzunmüddətli aktivin dəyərinin xidmət illəri üzrə bölüşdürülməsi. Pulsuz xərcdir.', ''],
  margin: ['Marja', 'Mənfəətin gəlirdəki payı faizlə. Məsələn, EBITDA marjası 20% o deməkdir ki, hər 100 avro gəlirdən 20 avro EBITDA qalır.', ''],
  arr: ['ARR', 'Annual Recurring Revenue: abunələr üzrə illik təkrarlanan gəlir. SaaS şirkətlərinin əsas göstəricisi.', ''],
  dso: ['DSO', 'Days Sales Outstanding: müştərilərin orta hesabla neçə günə ödəniş etdiyi. Nə qədər azdırsa, pul bir o qədər tez qayıdır.', 'DSO = debitor borcu / gəlir × 365'],
  lbo: ['LBO', 'Leveraged Buyout: şirkətin böyük borc payı ilə satın alınması. Borc şirkətin öz pul axınları hesabına ödənilir və 3-7 ildən sonra satılır.', ''],
  ma: ['M&A', 'Mergers & Acquisitions: birləşmə və satın almalar. İnvestisiya bankları şirkətlərin alınması, satılması və birləşdirilməsi üzrə məsləhət verir.', ''],
  accr: ['Accretive', 'Sonra alıcının bir səhmə düşən mənfəətinin (EPS) artdığı sövdələşmə. Səhmlərlə ödənişdə bu, adətən alıcının P/E-si hədəfin P/E-sindən yüksək olduqda baş verir.', ''],
  dil: ['Dilutive', 'Sonra alıcının EPS-nin düşdüyü sövdələşmə. «Dilution» həm də yeni səhmlər buraxılarkən səhmdarların payının durulması deməkdir.', ''],
  moic: ['MOIC', 'Multiple on Invested Capital: qoyulmuş pulun neçə dəfə artdığı. 2,0x o deməkdir ki, 100 qoyub 200 almısınız.', 'MOIC = çıxış (equity) / giriş (equity)'],
  irr: ['IRR', 'Internal Rate of Return: vaxtı nəzərə almaqla investisiyanın orta illik gəlirliliyi. Daha tez alınan pulun daha dəyərli olduğunu nəzərə alır.', 'IRR ≈ MOIC^(1/illər) − 1'],
  gw: ['Goodwill', 'Şirkətin satınalma qiyməti ilə onun müəyyən edilə bilən xalis aktivlərinin ədalətli dəyəri arasındakı fərq. Amortizasiya olunmur, lakin dəyərsizləşmə üçün yoxlanılır.', 'Goodwill = qiymət − xalis aktivlərin FV-si'],
  ipo: ['IPO', 'İlkin açıq yerləşdirmə: şirkət səhmləri birjada investorlara ilk dəfə satır. Banklar sövdələşməni təşkil edir və komissiya alır.', ''],
  cim: ['CIM', 'Confidential Information Memorandum: potensial alıcılar üçün şirkət haqqında ətraflı sənəd. Satışın əsas marketinq materialı.', ''],
  ioi: ['IOI', 'Indication of Interest: satışın ilk mərhələsində alıcının qeyri-rəsmi, məcburi olmayan təklifi.', ''],
  spa: ['SPA', 'Share Purchase Agreement: səhmlərin alqı-satqı müqaviləsi. Sövdələşmənin əsas hüquqi sənədi.', ''],
  gs: ['Greenshoe', 'Anderrayterin IPO zamanı yerləşdirmədən sonra qiyməti sabitləşdirmək üçün 15%-dək əlavə səhm yerləşdirmək opsionu.', ''],
  bf: ['Breakup fee', 'Hədəf rəqib təklifi qəbul etdikdə ödədiyi cərimə. İlk alıcını qoruyur.', ''],
  sweep: ['Cash sweep', 'Şirkətin sərbəst pulunun borcun vaxtından əvvəl ödənilməsinə yönəldilməsi. LBO-da delevering-in əsas yolu.', ''],
  pik: ['PIK', 'Payment-in-kind: faizlər pulla ödənilmir, borcun əsas məbləğinə əlavə olunur. Pul şirkətdə qalır, lakin borc artır.', ''],
  mac: ['MAC', 'Material Adverse Change: hədəfin vəziyyəti əhəmiyyətli dərəcədə pisləşdikdə alıcıya sövdələşmədən çıxmağa imkan verən qeyd.', ''],
  exit: ['Exit', 'Çıxış: investorun qoyulmuş pulu mənfəətlə geri qaytarmaq üçün şirkəti və ya payını satması. Sponsor üçün adətən 3-7-ci ildə.', ''],
  spons: ['Sponsor', 'Maliyyə sponsoru: LBO-da şirkətləri satın alan private equity fondu.', ''],
  syn: ['Sinerjilər', 'Şirkətlərin birləşməsindən əlavə dəyər. Cost sinerjilər (xərc qənaəti) revenue sinerjilərdən (çarpaz satış) daha etibarlıdır.', ''],
  cp: ['Nəzarət premiyası', 'Alıcının şirkət üzərində nəzarəti əldə etmək üçün səhmin bazar qiymətinə əlavə ödədiyi artım. Adətən 20-40%.', ''],
  delev: ['Deleveraging', 'Borcun ödənilməsi hesabına borc yükünün azaldılması. LBO gəlirliliyinin üç mənbəyindən biri.', ''],
  lock: ['Lock-up', 'İnsayderlərə IPO-dan sonra 90-180 gün müddətində səhm satmağın qadağan edilməsi. Qiyməti satış təzyiqindən qoruyur.', ''],
  earn: ['Earn-out', 'Şirkət razılaşdırılmış nəticələrə çatarsa, sonradan ödənilən sövdələşmə qiymətinin bir hissəsi.', ''],
  book: ['Bookrunner', 'Sifariş kitabını aparan və səhm və ya istiqrazların yerləşdirilməsini təşkil edən bank.', ''],
  uw: ['Anderrayter', 'Qiymətli kağızların yerləşdirilməsinə zəmanət verən və yerləşdirilməyən hissənin riskini öz üzərinə götürən bank.', ''],
  teaser: ['Teaser', 'Satışın əvvəlində potensial alıcılara göndərilən şirkət haqqında bir-iki səhifəlik qısa anonim icmal.', ''],
  dr: ['Data room', 'Ciddi alıcıların yoxlama (due diligence) üçün buraxıldığı şirkət sənədlərinin qorunan anbarı.', ''],
};
